'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {build}=require('../import/importer'),fixture=require('./fixtures/drop-source.json');
const {resolveConversion}=require('../domain/measurements'),{costIngredient}=require('../domain/costing'),{Exact:E}=require('../domain/exact');
const {DomainService}=require('../service'),{MemoryRepository}=require('../repository/memory'),{itemRecord}=require('../review/items'),{management}=require('../review/management');
const at='2026-09-18T20:40:26.000Z',admin={id:'owner',role:'ADMIN'};
async function data(){const r=await build(fixture,{activationAt:at});const s=r.state,id=s.ingredients.find(i=>i.name==='Pernod').id;return {r,s,id,service:new DomainService(new MemoryRepository(s),{clock:()=>at})};}
for(const q of ['1','2','5','6'])test('drop graph: exact '+q+' drop conversion',async()=>{const {s,id}=await data(),c=resolveConversion(s,{ingredientId:id,quantity:q,fromUnit:'drop',toUnit:'fl_oz_us',at,knownAt:at});assert.equal(c.status,'resolved');assert.ok(c.amount.eq(E.of('0.00113636').mul(q)));assert.equal(c.measurementIds.length,1);});
test('drop costing: ordinary graph prices real Pernod recipe line',async()=>{const {s,id,r}=await data(),p=s.purchaseOptions.find(p=>p.ingredientId===id),price=s.prices.find(x=>x.purchaseOptionId===p.id),cost=costIngredient(s,{ingredientId:id,quantity:'6',unit:'drop',at,knownAt:at});assert.ok(cost.completeCost.eq(E.of(price.amount).div(p.contentQuantity).mul('0.00113636').mul('6')));assert.notEqual(r.reconciliation[0].completeCost,null);assert.ok(!r.records.some(r=>r.issues.some(i=>i.concept==='Measurement')));});
test('drop history: future revisions do not rewrite earlier conversion or known-at results',async()=>{const {s,id,service}=await data(),m=s.measurements.find(m=>m.fromUnit==='drop');const past=resolveConversion(s,{ingredientId:id,quantity:'1',fromUnit:'drop',toUnit:'fl_oz_us',at:'2026-01-01T00:00:00.000Z',knownAt:at});assert.equal(past.status,'unresolved_missing_measurement');service.clock=()=> '2026-09-19T00:00:00.000Z';await service.execute(admin,'addMeasurement',{ingredientId:id,measurementKey:m.measurementKey,fromQuantity:'1',fromUnit:'drop',toQuantity:'0.002',toUnit:'fl_oz_us',effectiveAt:service.clock(),provenance:{kind:'manual',reference:'test'}});const next=await service.repository.read();for(const [time,known,want] of [[at,service.clock(),'0.00113636'],[service.clock(),at,'0.00113636'],[service.clock(),service.clock(),'0.002']])assert.ok(resolveConversion(next,{ingredientId:id,quantity:'1',fromUnit:'drop',toUnit:'fl_oz_us',at:time,knownAt:known}).amount.eq(want));});
test('unit visibility: Admin and Manager see authoritative catalog unit and resolvable detail conversions only',async()=>{const {service,id}=await data();for(const role of ['ADMIN','MANAGER']){const a={id:'review',role},detail=await itemRecord(service,a,id),catalog=await management(service,a);assert.equal(detail.unitInfo.unit,'fl_oz_us');assert.equal(catalog.items.find(i=>i.id===id).baseUnit,'fl_oz_us');assert.equal(detail.unitInfo.conversions.find(c=>c.unit==='drop').equivalent,'0.001136360000');assert.ok(!detail.unitInfo.conversions.some(c=>c.unit==='op:bottle'));assert.equal(detail.unitInfo.direct.length,1);}});
test('unit authorization: Staff and Lead retain safe projections and cannot write conversions',async()=>{const {service,id}=await data();for(const role of ['STAFF','LEAD']){const a={id:'count',role},detail=await itemRecord(service,a,id),catalog=await management(service,a);assert.equal(detail.unitInfo,undefined);assert.equal(catalog.items.find(i=>i.id===id).baseUnit,undefined);await assert.rejects(service.execute(a,'addMeasurement',{ingredientId:id,fromQuantity:'1',fromUnit:'drop',toQuantity:'0.00113636',toUnit:'fl_oz_us'}),{code:'forbidden'});}});
test('unit graph: explicit bottle measurement becomes visible, conflicting drops do not produce a false equivalent',async()=>{const {service,id}=await data();await service.execute(admin,'addMeasurement',{ingredientId:id,fromQuantity:'1',fromUnit:'op:bottle',toQuantity:'25.3605',toUnit:'fl_oz_us',provenance:{kind:'manual',reference:'test'}});assert.equal((await itemRecord(service,admin,id)).unitInfo.conversions.find(c=>c.unit==='op:bottle').equivalent,'25.360500000000');await service.execute(admin,'addMeasurement',{ingredientId:id,fromQuantity:'1',fromUnit:'drop',toQuantity:'0.002',toUnit:'fl_oz_us',provenance:{kind:'manual',reference:'test'}});assert.ok(!(await itemRecord(service,admin,id)).unitInfo.conversions.some(c=>c.unit==='drop'));});
