'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {configuration}=require('../deploy/runtime'),{createReviewServer}=require('../review/server'),{createUser}=require('../review/auth');
const {DomainService}=require('../service'),{MemoryRepository}=require('../repository/memory'),{seed}=require('../review/seed');
let server,base,users,password,service;
const origin='https://wahi-reporting-system.onrender.com';
before(async()=>{password=crypto.randomBytes(30).toString('base64url');users=await Promise.all(['ADMIN','MANAGER','LEAD','STAFF'].map(r=>createUser(r.toLowerCase(),r,password)));service=new DomainService(new MemoryRepository());await seed(service);server=createReviewServer({service,users,runtime:{hosted:true,origin,environment:'production'}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;});
after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});
async function request(path,{body,cookie,csrf,requestOrigin=origin,host=new URL(origin).host}={}){return new Promise((resolve,reject)=>{const req=require('node:http').request(base+path,{method:body===undefined?'GET':'POST',headers:{Host:host,Origin:requestOrigin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})}},res=>{let text='';res.on('data',b=>text+=b);res.on('end',()=>resolve({status:res.statusCode,headers:{get:k=>Array.isArray(res.headers[k])?res.headers[k][0]:res.headers[k]??null},text}));});req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body));});}
async function login(role){const r=await request('/api/login',{body:{username:role.toLowerCase(),password}});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.match(cookie,/^__Host-wahi_session=/);assert.match(cookie,/HttpOnly; SameSite=Strict; Path=\/; Max-Age=28800; Secure/);const me=JSON.parse((await request('/api/me',{cookie})).text);return {cookie,csrf:me.csrf};}
test('hosted startup fails closed for missing secrets, account hashes or wrong database/origin',()=>{const env={WAHI_PUBLIC_ORIGIN:origin,WAHI_ENVIRONMENT:'production',WAHI_DATABASE_URL:'postgresql://u:p@dpg-d6qot2fkijhs73ba5itg-a/wahi_reporting_db',WAHI_INTEGRATION_KEY_BASE64:crypto.randomBytes(32).toString('base64'),WAHI_AUTH_USERS_JSON:JSON.stringify(users)};assert.equal(configuration(env).environment,'production');for(const key of Object.keys(env))assert.throws(()=>configuration({...env,[key]:''}));assert.throws(()=>configuration({...env,WAHI_PUBLIC_ORIGIN:'http://localhost'}));assert.throws(()=>configuration({...env,WAHI_DATABASE_URL:'postgresql://u:p@localhost/postgres'}));assert.throws(()=>configuration({...env,WAHI_AUTH_USERS_JSON:JSON.stringify([{...users[0],password:'not-allowed'}])}));});
test('hosted public HTML contains no review instructions, credentials or automatic sign-in',async()=>{const r=await request('/');assert.equal(r.status,200);assert.match(r.text,/Log in to Wahi/);assert.doesNotMatch(r.text,/OWNER REVIEW|Owner review|local review credentials|Production logins are separate/);assert.equal(r.headers.get('x-wahi-review'),null);assert.equal((await request('/api/admin')).status,401);assert.equal((await request('/api/me')).status,401);});
test('hosted sessions use secure cookies and logout invalidates access',async()=>{const auth=await login('ADMIN');const me=JSON.parse((await request('/api/me',auth)).text);assert.equal(me.hosted,true);assert.equal(me.environment,'production');assert.equal((await request('/api/admin',auth)).status,200);assert.equal((await request('/api/logout',{...auth,body:{}})).status,200);assert.equal((await request('/api/me',auth)).status,401);});
test('hosted authorization, origin and CSRF checks remain authoritative',async()=>{for(const role of ['MANAGER','LEAD','STAFF']){const a=await login(role);assert.equal((await request('/api/admin',a)).status,403);assert.equal((await request('/api/admin/integrations/toast',a)).status,403);if(role!=='MANAGER'){const view=JSON.parse((await request('/api/management',a)).text);assert.ok(view.items.every(i=>!Object.hasOwn(i,'cost')&&!Object.hasOwn(i,'purchase')));assert.ok(view.recipes.every(r=>!Object.hasOwn(r,'cost')));}}const a=await login('ADMIN');assert.equal((await request('/api/logout',{...a,body:{},requestOrigin:'https://attacker.example'})).status,403);assert.equal((await request('/api/logout',{...a,csrf:'bad',body:{}})).status,403);assert.equal((await request('/api/me',{...a,host:'attacker.example'})).status,403);});
test('hosted has no review runtime/static data or debug routes',async()=>{const a=await login('ADMIN');for(const p of ['/review/.runtime/access.json','/.env','/api/debug']){const r=await request(p,a);assert.equal(r.status,404);assert.doesNotMatch(r.text,/stack|postgresql:\/\//);}});
