'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {DomainService}=require('../service'),{MemoryRepository}=require('../repository/memory');
const {management}=require('../review/management'),{saveItem}=require('../review/items');
const table=require('../review/public/table-model');
const admin={id:'admin',role:'ADMIN'},manager={id:'manager',role:'MANAGER'},provenance={kind:'manual',reference:'Automated test only'};
function fixture(){let n=0;const service=new DomainService(new MemoryRepository(),{clock:()=>new Date(Date.UTC(2026,8,18,0,0,0,n++)).toISOString()});return {service,run:(c,d,a=admin)=>service.execute(a,c,{...d,provenance})};}
async function prep(f){const p=await saveItem(f.service,admin,{kind:'purchase',name:'Sugar',description:'',category:'Dry',active:true,purchase:{label:'Bag',contentQuantity:'100',contentUnit:'g',amount:'10',currency:'USD',supplierId:null}});const output=await saveItem(f.service,admin,{kind:'recipe',name:'Syrup',description:'',category:'',active:true,recipe:{outputQuantity:'100',outputUnit:'mL',lines:[{ingredientId:p.id,quantity:'100',unit:'g'}],steps:['Mix']}});const s=await f.service.repository.read();return {p,output,recipe:s.recipes.find(r=>r.outputIngredientId===output.id)};}
test('management: configurable category identity, ordering, renaming and archival retain assignments and audits',async()=>{const f=fixture(),{recipe}=await prep(f),cat=await f.run('createRecipeCategory',{name:'Prep',sortOrder:2},manager);await f.run('setRecipeCategory',{recipeId:recipe.id,categoryId:cat.id});await f.run('updateRecipeCategory',{categoryId:cat.id,name:'Preparation',sortOrder:1,active:false},manager);const s=await f.service.repository.read(),m=await management(f.service,manager);assert.equal(s.recipeCategoryAssignments.length,1);assert.equal(m.recipes[0].category.id,cat.id);assert.equal(m.recipes[0].category.active,false);assert.equal(m.recipes[0].category.name,'Preparation');assert.equal(s.audit.filter(a=>a.entityId===cat.id).length,2);assert.equal(s.audit.find(a=>a.entityId===cat.id&&a.previous)?.previous.name,'Prep');await assert.rejects(f.run('setRecipeCategory',{recipeId:recipe.id,categoryId:cat.id}));await f.run('setRecipeCategory',{recipeId:recipe.id,categoryId:null});assert.equal((await f.service.repository.read()).recipeCategoryAssignments.length,2);assert.equal((await management(f.service,admin)).recipes[0].category,null);});
test('management: recipe detail preserves output link, recursive prep cost and exact mapped portion percentage',async()=>{const f=fixture(),{output,recipe}=await prep(f),menu=await f.run('createMenuItem',{name:'Served syrup'});await f.run('setMenuMapping',{menuItemId:menu.id,recipeId:recipe.id,quantity:'10',unit:'mL'});await f.run('setSellingPrice',{menuItemId:menu.id,amount:'4',currency:'USD'});let m=await management(f.service,admin),r=m.recipes[0];assert.equal(r.outputIngredientId,output.id);assert.equal(r.cost.completeCost,'10.000000000000');assert.equal(r.menus[0].costPercentage,'25.0000');assert.equal(m.items.find(i=>i.id===output.id).finished,true);await saveItem(f.service,admin,{kind:'recipe',name:'Nested',description:'',category:'',active:true,recipe:{outputQuantity:'1',outputUnit:'each',lines:[{ingredientId:output.id,quantity:'10',unit:'mL'}],steps:[]}});m=await management(f.service,admin);assert.equal(m.items.find(i=>i.id===output.id).finished,false);assert.equal(m.recipes.find(r=>r.name==='Nested').cost.completeCost,'1.000000000000');});
for(const role of ['STAFF','LEAD'])test(`management: ${role} cannot manage categories or receive internal costs`,async()=>{const f=fixture();await prep(f);const actor={id:role,role};const m=await management(f.service,actor);function inspect(x){if(!x||typeof x!=='object')return;for(const [k,v]of Object.entries(x)){assert.ok(!['cost','purchase','costPercentage','knownSubtotal','laborSubtotal','materialSubtotal'].includes(k));inspect(v);}}inspect(m);for(const command of ['createRecipeCategory','updateRecipeCategory','setRecipeCategory'])await assert.rejects(f.run(command,{},actor),{code:'forbidden'});});
test('management: item table supports combined search, type, category, active state and stable ascending/descending sorting',()=>{const rows=[{name:'Lime',active:true,itemKind:'Purchased',category:'Produce'},{name:'Apple',active:true,itemKind:'Purchased',category:'Produce'},{name:'Old lime',active:false,itemKind:'Prepared',category:'Prep'},{name:'Cocktail',active:true,finished:true}];assert.deepEqual(table.select(rows).map(r=>r.name),['Apple','Lime']);assert.deepEqual(table.select(rows,{query:'lime',type:'Purchased',category:'Produce'}).map(r=>r.name),['Lime']);assert.deepEqual(table.select(rows,{direction:'desc'}).map(r=>r.name),['Lime','Apple']);assert.equal(table.select(rows,{state:'inactive'})[0].name,'Old lime');assert.equal(table.select(rows,{category:'missing'}).length,0);});
test('management: recipe search and category identity filtering survive rename and inactive categories',()=>{const rows=[{name:'Syrup',active:true,category:{id:'a',name:'Preparation',active:false}},{name:'Cocktail',active:true,category:{id:'b',name:'Drinks',active:true}},{name:'Old syrup',active:false,category:{id:'a',name:'Preparation',active:false}}];assert.equal(table.select(rows,{query:'syr',category:'a'})[0].name,'Syrup');assert.equal(table.select(rows,{state:'all',category:'a'}).length,2);assert.equal(table.select(rows,{query:'drinks'})[0].name,'Cocktail');});
test('management: blank, zero and mismatched-currency selling prices never invent cost percentages',async()=>{const f=fixture(),{recipe}=await prep(f),m=await f.run('createMenuItem',{name:'Menu'});await f.run('setMenuMapping',{menuItemId:m.id,recipeId:recipe.id,quantity:'1',unit:'mL'});for(const price of [null,{amount:'0',currency:'USD'},{amount:'5',currency:'EUR'}]){if(price)await f.run('setSellingPrice',{menuItemId:m.id,...price});assert.equal((await management(f.service,admin)).recipes[0].menus[0].costPercentage,null);}});
test('management: compact table renderer supplies semantic headers, linked records, empty state and scroll region',()=>{const vm=require('node:vm'),fs=require('node:fs'),context={esc:v=>String(v??'').replaceAll('<','&lt;'),api:()=>new Promise(()=>{})};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../review/public/management-ui.js'),'utf8'),context);const html=context.compactTable(['Item','Status'],['<tr><th scope="row"><a href="#catalog/123">Lime</a></th><td>Active</td></tr>']);assert.match(html,/<table class="admin-table">/);assert.match(html,/<th scope="col">Item/);assert.match(html,/role="region"/);assert.match(html,/tabindex="0"/);assert.match(html,/<a href="#catalog\/123">Lime/);assert.match(context.compactTable(['Item'],[]),/No matching records/);});
test('management: uncategorized filter includes only unassigned recipes and item categories',()=>{assert.equal(table.select([{name:'A',active:true,category:null},{name:'B',active:true,category:{id:'x',name:'Prep'}}],{category:'__none'}).length,1);});
test('management: new recipe and category assignment save atomically through existing item workflow',async()=>{const f=fixture(),cat=await f.run('createRecipeCategory',{name:'Automated Prep'}),input={kind:'recipe',recipeCategoryId:cat.id,name:'New recipe',description:'',category:'',active:true,recipe:{outputQuantity:null,outputUnit:'mL',lines:[],steps:[]}};const saved=await saveItem(f.service,manager,input),m=await management(f.service,manager);assert.equal(m.recipes.find(r=>r.outputIngredientId===saved.id).category.id,cat.id);await f.run('updateRecipeCategory',{categoryId:cat.id,name:'Automated Prep',sortOrder:0,active:false});const before=await f.service.repository.read();await assert.rejects(saveItem(f.service,manager,input));assert.deepEqual(await f.service.repository.read(),before);});
