'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {DomainService}=require('../service'),{MemoryRepository}=require('../repository/memory'),{createRecipe}=require('../review/recipe-workflow'),{saveItem}=require('../review/items'),{view}=require('../review/views');
const admin={id:'test-admin',role:'ADMIN'},provenance={kind:'manual'};
function fixture(){let n=0;const s=new DomainService(new MemoryRepository(),{clock:()=>new Date(Date.UTC(2026,8,19,0,0,0,n++)).toISOString()});return {s,run:(c,d)=>s.execute(admin,c,{provenance,...d})};}
const formula=id=>({name:'Wahi recipe',description:'Notes',recipeCategoryId:null,recipe:{outputQuantity:'10',outputUnit:'each',lines:[{ingredientId:id,quantity:'2',unit:'each'}],steps:[' Mix ','  ','Serve']}});
async function bought(f,name='Purchased backup'){return saveItem(f.s,admin,{name,description:'',category:'',active:true,kind:'purchase',purchase:{label:'pack',contentQuantity:'10',contentUnit:'each',amount:'5',currency:'USD',supplierId:null}});}
test('recipe creation: new active output identity and recipe basis are automatic; steps trimmed',async()=>{const f=fixture(),p=await bought(f),r=await createRecipe(f.s,admin,formula(p.id)),s=await f.s.repository.read();assert.equal(s.ingredients.length,2);assert.equal(s.recipes[0].outputIngredientId,r.id);assert.equal(s.recipes[0].active,true);assert.equal(s.ingredients.find(i=>i.id===r.id).active,true);assert.equal(s.ingredients.find(i=>i.id===r.id).category,'');assert.equal(s.bases.find(b=>b.ingredientId===r.id).kind,'recipe');assert.deepEqual(s.recipeRevisions[0].steps.map(x=>x.instruction),['Mix','Serve']);assert.equal((await view(f.s,admin,'recipe',r.recipeId)).recipe.cost.completeCost,'1.000000000000');});
test('recipe creation: purchased backup cannot be targeted; separate house recipe can coexist',async()=>{const f=fixture(),p=await bought(f,'Orgeat');await assert.rejects(createRecipe(f.s,admin,{...formula(p.id),targetId:p.id,name:'Orgeat'}),{code:'invalid_recipe_target'});await createRecipe(f.s,admin,{...formula(p.id),name:'Wahi Orgeat'});const s=await f.s.repository.read();assert.equal(s.ingredients.length,2);assert.equal(s.bases.find(b=>b.ingredientId===p.id).kind,'purchase');});
test('recipe creation: blank placeholders and forged internal controls rejected atomically',async()=>{const f=fixture(),p=await bought(f),base=formula(p.id),before=await f.s.repository.read();for(const d of [{...base,outputIngredientId:p.id},{...base,active:false},{...base,category:'hidden'},{...base,recipe:{...base.recipe,outputUnit:''}},{...base,recipe:{...base.recipe,outputQuantity:null}},{...base,recipe:{...base.recipe,lines:[]}},{...base,recipe:{...base.recipe,lines:[{ingredientId:'',quantity:'',unit:''}]}},{...base,recipe:{...base.recipe,lines:[{ingredientId:p.id,quantity:'',unit:'each'}]}}])await assert.rejects(createRecipe(f.s,admin,d));assert.deepEqual(await f.s.repository.read(),before);});
test('recipe creation: normalized duplicate returns existing recipe without merging or writes',async()=>{const f=fixture(),p=await bought(f),r=await createRecipe(f.s,admin,{...formula(p.id),name:'Demerara Syrup'}),before=await f.s.repository.read(),duplicate=await createRecipe(f.s,admin,{...formula(p.id),name:'  DEMERARA   SYRUP  '});assert.equal(duplicate.duplicate.id,r.recipeId);assert.deepEqual(await f.s.repository.read(),before);});
test('recipe creation: concurrent normalized duplicate permits only one new identity',async()=>{const f=fixture(),p=await bought(f),r=await Promise.all([createRecipe(f.s,admin,formula(p.id)),createRecipe(f.s,admin,formula(p.id))]);assert.equal(r.filter(x=>x.duplicate).length,1);assert.equal((await f.s.repository.read()).recipes.length,1);});
test('resolution: contextual recipe preserves existing ID and recalculates dependent cost',async()=>{const f=fixture(),p=await bought(f),missing=await f.run('createIngredient',{name:'Unresolved component'}),parent=await createRecipe(f.s,admin,{...formula(missing.id),name:'Parent'}),before=await view(f.s,admin,'item',missing.id);assert.equal(before.kind,'Unresolved Item');assert.equal(before.resolution.createRecipe,true);assert.equal(before.dependentRecipes[0].id,parent.recipeId);assert.ok(before.cost.blockers[0].actions.some(x=>x.href==='recipes/new?item='+missing.id));const r=await createRecipe(f.s,admin,{...formula(p.id),name:'Unresolved component',targetId:missing.id});assert.equal(r.id,missing.id);assert.equal((await f.s.repository.read()).ingredients.length,3);assert.equal((await view(f.s,admin,'recipe',parent.recipeId)).recipe.cost.completeCost,'0.200000000000');});
test('resolution: Add Purchasing targets existing identity and recalculates parent',async()=>{const f=fixture(),missing=await f.run('createIngredient',{name:'Missing purchase'}),parent=await createRecipe(f.s,admin,formula(missing.id)),i=await view(f.s,admin,'item',missing.id);assert.equal(i.resolution.addPurchasing,true);assert.ok(i.cost.blockers[0].actions.some(x=>x.href.includes('?action=purchasing')));await saveItem(f.s,admin,{id:missing.id,kind:'purchase',name:'Missing purchase',description:'',category:'',active:true,purchase:{label:'pack',contentQuantity:'1',contentUnit:'each',amount:'3',currency:'USD',supplierId:null}});assert.equal((await view(f.s,admin,'recipe',parent.recipeId)).recipe.cost.completeCost,'6.000000000000');assert.equal((await f.s.repository.read()).ingredients.length,2);});
test('resolution: stale contextual target cannot replace new purchasing configuration',async()=>{const f=fixture(),missing=await f.run('createIngredient',{name:'Pending'}),p=await bought(f);assert.equal((await view(f.s,admin,'item',missing.id)).resolution.createRecipe,true);await saveItem(f.s,admin,{id:missing.id,kind:'purchase',name:'Pending',description:'',category:'',active:true,purchase:{label:'pack',contentQuantity:'1',contentUnit:'each',amount:'1',currency:'USD',supplierId:null}});await assert.rejects(createRecipe(f.s,admin,{...formula(p.id),targetId:missing.id,name:'Pending'}),{code:'invalid_recipe_target'});});
test('resolution: multiple actual blockers have accurate messages and distinct actions',async()=>{const f=fixture(),p=await bought(f),missing=await f.run('createIngredient',{name:'Missing'}),d=formula(missing.id);d.recipe.lines.push({ingredientId:p.id,quantity:'1',unit:'mL'});const r=await createRecipe(f.s,admin,d),v=(await view(f.s,admin,'recipe',r.recipeId)).recipe;assert.equal(v.cost.blockers.length,2);const conversion=v.cost.blockers.find(b=>b.reason==='unresolved_missing_measurement');assert.equal(conversion.message,'Missing conversion');assert.equal(conversion.actions[0].label,'Configure Measurements');assert.equal(v.cost.blockers.find(b=>b.reason==='missing_cost_basis').message,'No cost basis');});
test('resolution: conversion correction recalculates parent without retained unresolved cache',async()=>{const f=fixture(),p=await bought(f),d=formula(p.id);d.recipe.lines[0].unit='mL';const r=await createRecipe(f.s,admin,d);assert.equal((await view(f.s,admin,'recipe',r.recipeId)).recipe.cost.completeCost,null);await f.run('addMeasurement',{ingredientId:p.id,fromQuantity:'1',fromUnit:'each',toQuantity:'2',toUnit:'mL'});assert.equal((await view(f.s,admin,'recipe',r.recipeId)).recipe.cost.completeCost,'0.500000000000');});
test('recipe editing: steps and yields remain immutable revisions; labor and measurements available later',async()=>{const f=fixture(),p=await bought(f),r=await createRecipe(f.s,admin,formula(p.id));await f.run('reviseRecipe',{recipeId:r.recipeId,outputQuantity:'20',outputUnit:'each',lines:formula(p.id).recipe.lines,steps:['Updated']});await f.run('addMeasurement',{ingredientId:r.id,fromQuantity:'1',fromUnit:'each',toQuantity:'2',toUnit:'mL'});await f.run('setLabor',{ingredientId:r.id,kind:'fixed',amount:'2',currency:'USD',outputQuantity:'20',outputUnit:'each'});const s=await f.s.repository.read();assert.equal(s.recipeRevisions.length,2);assert.equal(s.recipeRevisions[0].steps[0].instruction,'Mix');assert.equal(s.measurements.length,1);assert.equal(s.labor.length,1);});
for(const role of ['STAFF','LEAD'])test('resolution authorization: '+role+' cannot create or see blocker actions/costs',async()=>{const f=fixture(),p=await bought(f),actor={id:role,role};await assert.rejects(createRecipe(f.s,actor,formula(p.id)),{code:'forbidden'});const i=await view(f.s,actor,'item',p.id);for(const k of ['resolution','dependentRecipes','cost'])assert.equal(i[k],undefined);});
test('recipe creation: category organization and finished visibility remain separate',async()=>{const f=fixture(),p=await bought(f),cat=await f.run('createRecipeCategory',{name:'Final'}),r=await createRecipe(f.s,admin,{...formula(p.id),recipeCategoryId:cat.id}),m=await f.run('createMenuItem',{name:'Menu'});assert.equal((await view(f.s,admin,'recipe',r.recipeId)).recipe.category.name,'Final');await f.run('setMenuMapping',{menuItemId:m.id,recipeId:r.recipeId,quantity:'10',unit:'each'});assert.ok(!(await view(f.s,admin,'items')).items.some(i=>i.id===r.id));});
test('recipe creation UI: direct form blank placeholders no output machinery and retained category/steps',async()=>{const source=fs.readFileSync(require.resolve('../review/public/management-ui.js'),'utf8'),nodes={},forms={},p={id:'00000000-0000-4000-8000-000000000001',name:'Item',active:true},ctx={can:()=>true,refresh:async()=>{},catalog:{ingredients:[p],recipes:[],recipeCategories:[]},$:id=>nodes[id]||(nodes[id]={}),link:(h,t)=>t,esc:String,field:(l,n,v='')=>`<input name="${n}" value="${v}">${l}`,select:(l,n,opts,v='')=>`${l}<select name="${n}">${opts.map(([id,name])=>`<option value="${id}"${id===v?' selected':''}>${name}</option>`).join('')}</select>`,units:['each','mL'],unitLabel:x=>x,document:{querySelectorAll:()=>[]},bind:()=>{},form:(id,fn)=>forms[id]=fn,window:{addEventListener:()=>{}},URLSearchParams};vm.createContext(ctx);vm.runInContext(source,ctx);await vm.runInContext('newRecipePage()',ctx);const html=nodes.main.innerHTML+nodes['new-recipe-lines'].innerHTML;assert.match(html,/Recipe Category/);assert.match(html,/Preparation steps/);assert.match(html,/Choose item/);assert.match(html,/Choose unit/);assert.match(html,/name="outputQuantity" value=""/);assert.match(html,/name="quantity0" value=""/);assert.doesNotMatch(html,/Output item|outputIngredientId|Effective Date|laborKind|fromQuantity|value="mL" selected/);assert.match(source,/await newRecipePage/);});
test('resolution: incomplete source yield offers contextual recipe and purchasing with accurate missing-yield reason',async()=>{const f=fixture(),p=await bought(f),missing=await f.run('createIngredient',{name:'Incomplete source'});await f.run('setYield',{ingredientId:missing.id,sourceIngredientId:p.id,sourceQuantity:null,sourceUnit:null,outputQuantity:null,outputUnit:null});const i=await view(f.s,admin,'item',missing.id);assert.equal(i.cost.blockers[0].message,'Missing yield');assert.equal(i.resolution.createRecipe,true);assert.equal(i.resolution.addPurchasing,true);assert.ok(i.cost.blockers[0].actions.some(a=>a.label==='Create Recipe'));const r=await createRecipe(f.s,admin,{...formula(p.id),targetId:missing.id,name:'Incomplete source'});assert.equal(r.id,missing.id);assert.equal((await view(f.s,admin,'item',missing.id)).cost.completeCost,'1.000000000000');});
test('resolution: complete source yield cannot be hijacked by contextual recipe',async()=>{const f=fixture(),p=await bought(f),i=await f.run('createIngredient',{name:'Complete source'});await f.run('setYield',{ingredientId:i.id,sourceIngredientId:p.id,sourceQuantity:'1',sourceUnit:'each',outputQuantity:'1',outputUnit:'each'});await assert.rejects(createRecipe(f.s,admin,{...formula(p.id),targetId:i.id,name:'Complete source'}),{code:'invalid_recipe_target'});});
