'use strict';
const {test,before,beforeEach,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),{Pool}=require('pg');
const {migrate}=require('../migrate'),{UserAccounts}=require('../accounts/service'),{createUser}=require('../review/auth'),{ResendEmail}=require('../integrations/resend'),{LaborService}=require('../labor/service'),{ManagementReports,configuration,eligibility}=require('../reports/service'),{local,scheduledInstant,due}=require('../reports/schedule'),{format}=require('../review/public/leadership-summary'),links=require('../review/public/deep-links');
const bin=process.env.WAHI_TEST_PG_BIN||'/opt/homebrew/opt/postgresql@16/bin',origin='https://wahi-reporting-system.onrender.com',password='Synthetic-management-tests-2026';let dir,pool,accounts,email,labor,reports,admin,user,now,messages,mode,credentials;
before(async()=>{dir=await fs.mkdtemp(path.join(os.tmpdir(),'wahi-reports-'));execFileSync(path.join(bin,'initdb'),['-D',path.join(dir,'data'),'--auth=trust','--username=wahi_test','--no-locale','-E','UTF8'],{stdio:'pipe'});execFileSync(path.join(bin,'pg_ctl'),['-D',path.join(dir,'data'),'-l',path.join(dir,'pg.log'),'-o',`-F -k ${dir} -h '' -p 55444`,'-w','start'],{stdio:'pipe'});pool=new Pool({host:dir,port:55444,user:'wahi_test',database:'postgres',max:5});await migrate(pool);credentials=await createUser('owner','ADMIN',password);admin={id:credentials.id,role:'ADMIN'};});
after(async()=>{await reports?.stop();await pool?.end();if(dir){execFileSync(path.join(bin,'pg_ctl'),['-D',path.join(dir,'data'),'-m','immediate','-w','stop'],{stdio:'pipe'});await fs.rm(dir,{recursive:true,force:true});}});
beforeEach(async()=>{
 await reports?.stop();await pool.query('TRUNCATE wahi_v2.users,wahi_v2.user_directory_state,wahi_v2.auth_credentials,wahi_v2.web_sessions,wahi_v2.integration_settings,wahi_v2.integration_audit,wahi_v2.management_reports,wahi_v2.labor_settings,wahi_v2.labor_sync_state,wahi_v2.labor_jobs,wahi_v2.labor_entries,wahi_v2.labor_standing_targets,wahi_v2.labor_sync_days CASCADE');
 now=Date.parse('2026-09-21T16:00:00Z');messages=[];mode='success';accounts=new UserAccounts(pool);await accounts.bootstrap([credentials]);user=(await accounts.create(admin,{name:'Manager',username:'manager',email:'manager@example.com',role:'MANAGER',status:'active'})).user;await pool.query('UPDATE wahi_v2.users SET email_verified_at=CURRENT_TIMESTAMP WHERE id=$1',[user.id]);
 await pool.query("INSERT INTO wahi_v2.management_reports(id,updated_at) VALUES('daily',$1),('weekly',$1);",[new Date(now)]);
 await pool.query("INSERT INTO wahi_v2.labor_settings(singleton,timezone,closeout_hour) VALUES(TRUE,'America/Los_Angeles',4);INSERT INTO wahi_v2.labor_sync_state(singleton) VALUES(TRUE)");
 await pool.query("INSERT INTO wahi_v2.labor_sync_days(business_date,synced_at) SELECT d,$1 FROM generate_series('2026-09-13'::date,'2026-09-21'::date,interval '1 day') d",[new Date(now)]);
 await pool.query("INSERT INTO wahi_v2.labor_standing_targets(id,effective_week,foh,boh,actor_id,recorded_at) VALUES($1,'2026-09-13',10,20,$2,CURRENT_TIMESTAMP)",[crypto.randomUUID(),admin.id]);
 for(const [area,hours]of [['FOH','6'],['BOH','25'],['Excluded','2'],['Unassigned','3']]){const job=crypto.randomUUID(),classification=crypto.randomUUID();await pool.query('INSERT INTO wahi_v2.labor_jobs(guid,name,active,synced_at) VALUES($1,$2,TRUE,$3)',[job,area,new Date(now)]);await pool.query("INSERT INTO wahi_v2.labor_classifications(id,job_guid,effective_date,area,actor_id,recorded_at) VALUES($1,$2,'2026-09-20',$3,$4,CURRENT_TIMESTAMP)",[classification,job,area,admin.id]);await pool.query('INSERT INTO wahi_v2.labor_job_mappings VALUES($1,$2)',[job,classification]);await pool.query("INSERT INTO wahi_v2.labor_entries(guid,restaurant_guid,business_date,job_guid,in_date,out_date,regular_hours,overtime_hours,breaks,deleted,synced_at) VALUES($1,$2,'2026-09-20',$3,'2026-09-20T12:00Z','2026-09-21T13:00Z',$4,0,'[]',FALSE,$5)",[crypto.randomUUID(),crypto.randomUUID(),job,hours,new Date(now)]);}
 email=new ResendEmail(pool,{environment:'production',key:crypto.randomBytes(32).toString('base64'),fetch:async(url,options)=>{messages.push({key:options.headers['Idempotency-Key'],body:JSON.parse(options.body)});if(mode==='throw')throw Error('secret provider detail');return {ok:mode==='success',status:mode==='reject'?422:503,json:async()=>({id:crypto.randomUUID()})};}});await email.save(admin,{expectedVersion:0,config:{enabled:true,senderName:'Wahi Hana',senderEmail:'no_reply@wahihana.com'},apiKey:'re_synthetic_test_secret_only'});labor=new LaborService(pool,{}, {clock:()=>now});reports=new ManagementReports(pool,labor,email,origin,{clock:()=>now,pause:async()=>{}});
});
async function save(extra={}){const id=extra.id||'daily',r=(await reports.definitions()).find(r=>r.id===id);return reports.save(admin,{id,expectedVersion:r.version,enabled:false,sendTime:null,weekday:null,timezone:'America/Los_Angeles',recipients:[user.id],sections:['labor'],...extra});}
async function manual(){const requestId=crypto.randomUUID();await save();const r=await reports.sendNow(admin,{id:'daily',requestId});await reports.running;return {...r,requestId};}
async function deliveries(){return (await pool.query('SELECT * FROM wahi_v2.management_deliveries ORDER BY id')).rows;}
test('reports: defaults disabled with no invented time/day and explicit Pacific timezone',async()=>{for(const r of await reports.definitions()){assert.equal(r.enabled,false);assert.equal(r.send_time,null);assert.equal(r.weekday,null);assert.equal(r.timezone,'America/Los_Angeles');}});
test('reports: daily and weekly configuration validation, version conflict and audited recipient changes',async()=>{await save({enabled:true,sendTime:'10:15'});await assert.rejects(save({id:'weekly',enabled:true,sendTime:'09:00'}));await save({id:'weekly',enabled:true,weekday:6,sendTime:'09:00'});await assert.rejects(save({timezone:'Unknown/Place'}));await assert.rejects(save({recipients:['missing']}));await assert.rejects(save({sections:['sales']}));await assert.rejects(save({expectedVersion:0}),e=>e.code==='revision_conflict');assert.equal((await reports.read(admin)).audit.length,2);});
test('reports: active verified Manager eligible; disabled missing unverified and lower roles rejected',()=>{const valid={status:'active',role:'MANAGER',email:'a@example.com',email_verified_at:new Date()};assert.equal(eligibility(valid),null);for(const [change,reason]of [[{status:'disabled'},'disabled'],[{email:null},'missing_email'],[{email_verified_at:null},'unverified_email'],[{role:'STAFF'},'no_labor_access'],[{role:'LEAD'},'no_labor_access']])assert.equal(eligibility({...valid,...change}),reason);});
test('reports: Manager Staff Lead cannot read configure preview or send, revoked Admin rechecked',async()=>{for(const role of ['MANAGER','STAFF','LEAD']){const a={id:user.id,role};for(const op of [()=>reports.read(a),()=>reports.preview(a,'daily'),()=>reports.sendNow(a,{id:'daily',requestId:crypto.randomUUID()}),()=>reports.save(a,{id:'daily',expectedVersion:0,enabled:false,sendTime:null,weekday:null,timezone:'UTC',recipients:[],sections:['labor']})])await assert.rejects(op(),e=>e.code==='forbidden');}await assert.rejects(reports.read({id:user.id,role:'ADMIN'}),e=>e.code==='forbidden');});
test('reports: canonical preview/dashboard equality FOH BOH Overall remaining OVER and uncapped percentage',async()=>{const p=await reports.preview(admin,'daily'),d=await labor.overview({id:user.id,role:'MANAGER'},{period:'this'});assert.deepEqual(p.sections[0].projection,d);assert.equal(p.summary,format(d,new Date(now).toISOString()));assert.match(p.summary,/FOH: 60.0% used \| 6.0 \/ 10.0 hrs \| 4.0 hrs remaining/);assert.match(p.summary,/BOH: 125.0% used \| 25.0 \/ 20.0 hrs \| 5.0 hrs OVER/);assert.match(p.summary,/Overall: 103.3% used \| 31.0 \/ 30.0 hrs \| 1.0 hrs OVER/);assert.match(p.summary,/3.0 labor hours are Unassigned/);assert.match(p.summary,/Excluded labor: 2.0/);assert.ok(p.text.includes(p.summary));assert.ok(p.html.includes('FOH: 60.0%'));assert.equal((await deliveries()).length,0);assert.equal((await reports.read(admin)).history.length,0);});
test('reports: weekly uses last completed week and historical target selection',async()=>{const p=await reports.preview(admin,'weekly');assert.equal(p.sections[0].projection.start,'2026-09-13');assert.equal(p.sections[0].projection.target.foh,'10');assert.equal(p.sections[0].projection.metrics.foh.display.used,'0.0');assert.ok(p.subject.includes('2026-09-13 – 2026-09-19'));});
test('reports: stale failed and missing-day warnings never claim unavailable hours are zero',async()=>{now+=11*60000;let p=await reports.preview(admin,'daily');assert.match(p.summary,/may be stale/);await pool.query("UPDATE wahi_v2.labor_sync_state SET error_code='toast_unavailable'");assert.match((await reports.preview(admin,'daily')).summary,/synchronization failed/);await pool.query("DELETE FROM wahi_v2.labor_sync_days WHERE business_date='2026-09-20'");p=await reports.preview(admin,'daily');assert.match(p.summary,/1 business dates are missing/);assert.match(p.summary,/does not mean zero/);assert.doesNotMatch(p.summary,/FOH: 0/);});
test('reports: manual send has frozen HTML/text, separate key, provider acceptance and safe history',async()=>{const r=await manual(),d=(await deliveries())[0];assert.equal(d.state,'accepted');assert.ok(d.accepted_at);assert.ok(d.provider_message_id);assert.equal(messages[0].key,'management/'+d.id);assert.match(messages[0].body.subject,/\[Manual\]/);await reports.sendNow(admin,{id:'daily',requestId:r.requestId});await reports.running;assert.equal(messages.length,1);const h=(await reports.read(admin)).history[0];assert.equal(h.kind,'manual');assert.equal(h.occurrence_id,r.occurrenceId);assert.doesNotMatch(JSON.stringify(h),/synthetic_test_secret|html|token=/);});
test('reports: due dispatch repeated and overlapping checks plus new runner do not duplicate',async()=>{await save({enabled:true,sendTime:'09:01'});now+=60000;await Promise.all([reports.tick(),reports.tick(),reports.tick()]);assert.equal(messages.length,1);await new ManagementReports(pool,labor,email,origin,{clock:()=>now,pause:async()=>{}}).tick();assert.equal(messages.length,1);assert.equal((await deliveries()).length,1);assert.equal((await reports.read(admin)).history[0].occurrence_key,'scheduled:2026-09-21');});
test('reports: weekly due dispatch uses configured weekday and no invented weekday',async()=>{await save({id:'weekly',enabled:true,weekday:1,sendTime:'09:01'});now+=60000;await reports.tick();assert.equal(messages.length,1);assert.match(messages[0].body.subject,/Weekly Management Summary/);assert.match(messages[0].body.text,/2026-09-13 – 2026-09-19/);});
test('reports: transient retry retains exact sender destination payload and provider idempotency key',async()=>{mode='throw';await manual();assert.equal((await deliveries())[0].state,'pending');await reports.tick();assert.equal(messages.length,1);now+=60000;mode='success';await reports.tick();assert.deepEqual(messages[0],messages[1]);assert.equal((await deliveries())[0].state,'accepted');});
test('reports: bounded retries and permanent provider rejection never marked sent',async()=>{mode='retry';await manual();for(const advance of [60000,300000,900000,900000]){now+=advance;await reports.tick();}assert.equal(messages.length,4);assert.equal((await deliveries())[0].state,'failed');assert.equal((await deliveries())[0].accepted_at,null);assert.equal((await deliveries())[0].failure_reason,'provider_rejected');});
test('reports: permanent rejection is terminal without retry storm',async()=>{mode='reject';await manual();now+=60000;await reports.tick();assert.equal(messages.length,1);assert.equal((await deliveries())[0].state,'failed');});
test('reports: uncertain outcome after downtime cannot retry outside Resend retention window',async()=>{mode='throw';await manual();now+=23*3600000;mode='success';await reports.tick();assert.equal(messages.length,1);assert.equal((await deliveries())[0].state,'unknown');assert.equal((await deliveries())[0].failure_reason,'retry_window_expired');});
test('reports: generation failures retry boundedly with sanitized history and no provider send',async()=>{labor.overview=async()=>{throw Error('secret raw database information');};await manual();for(const advance of [60000,300000,900000,900000]){now+=advance;await reports.tick();}const o=(await pool.query('SELECT * FROM wahi_v2.management_occurrences')).rows[0];assert.equal(o.attempts,4);assert.equal(o.state,'failed');assert.equal(o.failure_reason,'generation_unavailable');assert.equal(messages.length,0);});
test('reports: recipient disabled or email changed before retry skips old address',async()=>{mode='throw';await manual();await pool.query("UPDATE wahi_v2.users SET email='new@example.com',email_verified_at=NULL WHERE id=$1",[user.id]);now+=60000;await reports.tick();assert.equal(messages.length,1);assert.equal((await deliveries())[0].state,'skipped');assert.equal((await deliveries())[0].failure_reason,'unverified_email');});
test('reports: verified replacement email still cannot receive old frozen occurrence',async()=>{mode='throw';await manual();await pool.query("UPDATE wahi_v2.users SET email='new@example.com' WHERE id=$1",[user.id]);now+=60000;await reports.tick();assert.equal(messages.length,1);assert.equal((await deliveries())[0].failure_reason,'email_changed');});
test('reports: disabled and unverified selected accounts get skip evidence with no mail',async()=>{await save({enabled:true,sendTime:'09:01'});await pool.query("UPDATE wahi_v2.users SET status='disabled' WHERE id=$1",[user.id]);now+=60000;await reports.tick();assert.equal(messages.length,0);assert.equal((await deliveries())[0].failure_reason,'disabled');});
test('reports: removed recipients and disabled reports cancel pending scheduled retries',async()=>{mode='throw';await save({enabled:true,sendTime:'09:01'});now+=60000;await reports.tick();await save({enabled:false,sendTime:'09:01'});now+=60000;await reports.tick();assert.equal(messages.length,1);assert.equal((await deliveries())[0].failure_reason,'report_disabled');});
test('reports: schedule DST spring gap shifts forward and fall fold uses earliest single occurrence',()=>{const z='America/Los_Angeles';assert.equal(new Date(scheduledInstant('2026-03-08','02:30',z)).toISOString(),'2026-03-08T10:00:00.000Z');assert.equal(new Date(scheduledInstant('2026-11-01','01:30',z)).toISOString(),'2026-11-01T08:30:00.000Z');assert.equal(new Date(scheduledInstant('2026-01-10','09:00',z)).getUTCHours(),17);assert.equal(new Date(scheduledInstant('2026-07-10','09:00',z)).getUTCHours(),16);});
test('reports: due detection observes config start no retroactive sends and 24h catchup',()=>{const r={id:'daily',enabled:true,send_time:'09:00',timezone:'America/Los_Angeles',updated_at:'2026-09-20T00:00Z'};assert.equal(due(r,Date.parse('2026-09-21T15:59Z')).length,1);assert.equal(due(r,Date.parse('2026-09-21T16:00Z'))[0].key,'scheduled:2026-09-21');assert.equal(due({...r,updated_at:'2026-09-21T16:01Z'},Date.parse('2026-09-21T16:02Z')).length,0);assert.equal(due({...r,enabled:false},now).length,0);});
test('reports: deep link contains only period and destination preserves safe hash query',async()=>{const p=await reports.preview(admin,'daily'),u=new URL(p.link);assert.equal(u.origin,origin);assert.equal(links.safe(u.hash),u.hash);assert.deepEqual(links.selection(u.hash),{period:'custom',start:'2026-09-20',end:'2026-09-26'});assert.doesNotMatch(p.link,/token|password|session|username/);});
test('reports: reject external protocol-relative script data encoded and invalid period returns',()=>{for(const s of ['https://evil.test','//evil.test','javascript:alert(1)','data:text/html,a','/#time\\evil','#time?returnTo=https://evil.test','#time?period=custom&start=2026-02-30&end=2026-03-01','%23time','#time?period=this&start=2026-01-01&end=2026-01-07','#time?period=this&token=secret'])assert.equal(links.safe(s),null,s);assert.equal(links.safe('/#time'),'#time');assert.equal(links.safe('#time?period=last'),'#time?period=last');});
test('reports: provider configuration change blocks frozen message retry under another credential',async()=>{mode='throw';await manual();await email.save(admin,{expectedVersion:1,config:{enabled:true,senderName:'Updated',senderEmail:'no_reply@wahihana.com'}});now+=60000;await reports.tick();assert.equal(messages.length,1);assert.equal((await deliveries())[0].failure_reason,'integration_changed');});
test('reports: crash after provider acceptance before ledger commit replays same bytes and key',async()=>{await save();reports.kick=()=>{};await reports.sendNow(admin,{id:'daily',requestId:crypto.randomUUID()});await pool.query("CREATE FUNCTION wahi_v2.fail_report_acceptance() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.state='accepted' THEN RAISE EXCEPTION 'crash'; END IF; RETURN NEW; END; $$; CREATE TRIGGER fail_report_acceptance BEFORE UPDATE ON wahi_v2.management_deliveries FOR EACH ROW EXECUTE FUNCTION wahi_v2.fail_report_acceptance()");try{await assert.rejects(reports.tick());}finally{await pool.query('DROP TRIGGER fail_report_acceptance ON wahi_v2.management_deliveries; DROP FUNCTION wahi_v2.fail_report_acceptance()');}assert.equal(messages.length,1);assert.equal((await deliveries())[0].attempts,1);now+=60000;await reports.tick();assert.deepEqual(messages[0],messages[1]);assert.equal((await deliveries())[0].state,'accepted');});
test('reports: Copy Leadership Summary writes canonical text to clipboard and shows Copied',async()=>{const vm=require('node:vm'),source=await fs.readFile(path.join(__dirname,'../review/public/labor-ui.js'),'utf8'),d=await labor.overview(admin,{period:'this'}),nodes={main:{}},handlers={};let copied,notice;const context={WahiLeadership:{format},WahiCurrency:require('../review/public/currency'),Intl,Date,URLSearchParams,location:{hash:'#time'},can:()=>true,$:id=>nodes[id],esc:x=>String(x??''),api:async()=>d,button:(id,label)=>`<button id="${id}">${label}</button>`,link:()=>'',bind:(id,fn)=>{handlers[id]=fn;},form:()=>{},clearTimeout(){},setTimeout(){},navigator:{clipboard:{writeText:async text=>{copied=text;}}},notify:text=>{notice=text;}};vm.createContext(context);vm.runInContext(source,context);await vm.runInContext('laborPage(undefined,false)',context);await handlers['labor-copy']();assert.equal(notice,'Copied');assert.match(copied,/FOH: 60.0%/);assert.match(copied,/BOH: 125.0%/);assert.equal(copied,format(d,copied.split('\n')[2].slice('Generated: '.length)));});
test('reports: login routing retains safe destination for Admin/Manager and rejects lower roles',async()=>{const vm=require('node:vm'),source=(await fs.readFile(path.join(__dirname,'../review/public/waste-ui.js'),'utf8'))+'\n'+(await fs.readFile(path.join(__dirname,'../review/public/app.js'),'utf8'));for(const role of ['ADMIN','MANAGER','STAFF']){const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,innerHTML:'',addEventListener(){},reset(){}});return nodes.get(id);};const hash='#time?period=custom&start=2026-09-13&end=2026-09-19',context=vm.createContext({URLSearchParams,WahiLinks:links,document:{getElementById:node,querySelector:()=>node('banner')},window:{addEventListener(){}},location:{hash,search:''},console,setTimeout(){}});vm.runInContext(source,context);vm.runInContext("let laborSelection={};shellState={};renderShell=()=>{};laborPage=async()=>{$('main').innerHTML=can('labor.read')?'Time Management':'Access denied';}",context);await vm.runInContext('route()',context);assert.equal(node('login').hidden,false);context.testUser={id:'test',role,capabilities:role==='STAFF'?[]:['labor.read'],hosted:true};await vm.runInContext('loggedIn(testUser)',context);assert.equal(context.location.hash,hash);assert.equal(node('main').innerHTML,role==='STAFF'?'Access denied':'Time Management');await vm.runInContext('route()',context);assert.equal(node('workspace').hidden,false);}});
test('reports: HTTP authentication CSRF admin-only configuration and public assets',async()=>{const {createReviewServer}=require('../review/server'),{DomainService}=require('../service'),{MemoryRepository}=require('../repository/memory'),{NamedSessionStore}=require('../accounts/service');const server=createReviewServer({service:new DomainService(new MemoryRepository()),users:[credentials],accounts,sessionStore:new NamedSessionStore(pool),reports,labor});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;async function request(p,body,cookie,csrf){return fetch(base+p,{method:body?'POST':'GET',headers:{Origin:base,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},...(body?{body:JSON.stringify(body)}:{})});}try{assert.equal((await request('/api/admin/reports')).status,401);for(const asset of ['deep-links.js','leadership-summary.js','reports-ui.js'])assert.equal((await request('/'+asset)).status,200);const login=await request('/api/login',{username:'owner',password}),cookie=login.headers.get('set-cookie').split(';')[0],me=await (await request('/api/me',null,cookie)).json();assert.equal((await request('/api/admin/reports',null,cookie)).status,200);assert.equal((await request('/api/admin/reports/preview?id=daily',null,cookie)).status,200);assert.equal((await request('/api/admin/reports/send',{id:'daily',requestId:crypto.randomUUID()},cookie,'bad')).status,403);for(const role of ['MANAGER','STAFF','LEAD']){const p=await accounts.create(admin,{name:role,username:'http-'+role.toLowerCase(),email:null,role,status:'active'});await accounts.establish({token:p.setup.token,password});const l=await request('/api/login',{username:p.user.username,password}),c=l.headers.get('set-cookie').split(';')[0],m=await (await request('/api/me',null,c)).json();assert.equal((await request('/api/admin/reports',null,c)).status,403);assert.equal((await request('/api/admin/reports/preview?id=daily',null,c)).status,403);assert.equal((await request('/api/admin/reports/send',{id:'daily',requestId:crypto.randomUUID()},c,m.csrf)).status,403);assert.equal((await request('/api/labor/overview?period=last',null,c)).status,role==='MANAGER'?200:403);}}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
test('reports: real advancing clock dispatches newly enqueued occurrence in the same tick',async()=>{await save({enabled:true,sendTime:'09:01'});now+=60000;reports.clock=()=>now++;await reports.tick();assert.equal(messages.length,1);assert.equal((await deliveries())[0].state,'accepted');});
