'use strict';
const {test,before,beforeEach,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),http=require('node:http'),{execFileSync}=require('node:child_process'),{Pool}=require('pg');
const {migrate}=require('../migrate'),{UserAccounts,NamedSessionStore}=require('../accounts/service'),{createUser,verify}=require('../review/auth'),{createReviewServer}=require('../review/server'),{DomainService}=require('../service'),{MemoryRepository}=require('../repository/memory');
let directory,pool,accounts,store,admin,adminCredentials,server,base;const password='Named-account-test-password-2026',nextPassword='Another-test-password-2026',bin=process.env.WAHI_TEST_PG_BIN||'/opt/homebrew/opt/postgresql@16/bin';
before(async()=>{directory=await fs.mkdtemp(path.join(os.tmpdir(),'wahi-users-'));execFileSync(path.join(bin,'initdb'),['-D',path.join(directory,'data'),'--auth=trust','--username=wahi_test','--no-locale','-E','UTF8'],{stdio:'pipe'});execFileSync(path.join(bin,'pg_ctl'),['-D',path.join(directory,'data'),'-l',path.join(directory,'pg.log'),'-o',`-F -k ${directory} -h '' -p 55441`,'-w','start'],{stdio:'pipe'});pool=new Pool({host:directory,port:55441,user:'wahi_test',database:'postgres',max:5});await migrate(pool);adminCredentials=await createUser('owner','ADMIN',password);admin={id:adminCredentials.id,role:'ADMIN'};});
beforeEach(async()=>{await pool.query('TRUNCATE wahi_v2.users,wahi_v2.user_setup_tokens,wahi_v2.user_security_audit,wahi_v2.user_directory_state,wahi_v2.auth_credentials,wahi_v2.web_sessions,wahi_v2.login_limits CASCADE');accounts=new UserAccounts(pool);store=new NamedSessionStore(pool);await accounts.bootstrap([adminCredentials]);});
after(async()=>{if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}if(pool)await pool.end();if(directory){execFileSync(path.join(bin,'pg_ctl'),['-D',path.join(directory,'data'),'-m','immediate','-w','stop'],{stdio:'pipe'});await fs.rm(directory,{recursive:true,force:true});}});
const profile=(name='sarah',role='STAFF',status='active')=>({name,username:name,email:null,role,status});
async function create(name='sarah',role='STAFF',status='active'){return accounts.create(admin,profile(name,role,status));}
async function established(name='sarah',role='STAFF'){const r=await create(name,role);await accounts.establish({token:r.setup.token,password});return (await accounts.detail(admin,r.user.id)).user;}
async function session(username,pass=password){const u=await accounts.findLogin(username);if(!await verify(u,pass))return null;const token=crypto.randomUUID();await store.set(token,{user:u,csrf:crypto.randomUUID(),expires:Date.now()+3600000});return token;}
async function edit(u,changes={},actor=admin){const latest=(await accounts.detail(actor,u.id)).user;return accounts.mutate(actor,'update',{id:u.id,expectedVersion:latest.version,name:latest.name,username:latest.username,email:latest.email,role:latest.role,status:latest.status,...changes});}
async function action(u,command,actor=admin){return accounts.mutate(actor,command,{id:u.id,expectedVersion:(await accounts.detail(actor,u.id)).user.version});}

test('users: bootstrap preserves IDs/sessions and is never an environment overwrite',async()=>{const token=await session('owner');await accounts.bootstrap([{...adminCredentials,hash:'changed'}]);assert.ok(await store.get(token));assert.ok(await verify(await accounts.findLogin('owner'),password));assert.equal((await accounts.list(admin)).users[0].id,admin.id);});
test('users: normalized usernames prevent case-only duplicates; rename preserves attribution',async()=>{const r=await accounts.create(admin,{...profile(),username:'  SARAH  '});assert.equal(r.user.username,'sarah');await assert.rejects(create('Sarah'),e=>e.code==='account_conflict');await edit(r.user,{username:' New.Name '});assert.equal((await accounts.detail(admin,r.user.id)).user.username,'new.name');assert.equal((await accounts.detail(admin,r.user.id)).user.createdBy,admin.id);await assert.rejects(create('x'),e=>e.name==='ZodError');});
test('users: email optional, normalized, unique even disabled, validated and never implicitly verified',async()=>{const r=await accounts.create(admin,{...profile(),email:'  Sarah@Example.COM  '});assert.equal(r.user.email,'sarah@example.com');assert.equal(r.user.emailVerification,'unverified');assert.equal(r.user.emailVerifiedAt,null);await assert.rejects(accounts.create(admin,{...profile('other'),email:'SARAH@example.com'}),e=>e.code==='account_conflict');await assert.rejects(accounts.create(admin,{...profile('other'),email:'not-an-email'}),e=>e.name==='ZodError');await create('none-one');await create('none-two');await edit(r.user,{status:'disabled'});await assert.rejects(accounts.create(admin,{...profile('other'),email:'sarah@example.com'}),e=>e.code==='account_conflict');});
test('users: email changes clear future verification and reject forged verification/capabilities',async()=>{const r=await accounts.create(admin,{...profile(),email:'sarah@example.com'});await pool.query('UPDATE wahi_v2.users SET email_verified_at=CURRENT_TIMESTAMP WHERE id=$1',[r.user.id]);await edit(r.user,{email:'new@example.com'});assert.equal((await accounts.detail(admin,r.user.id)).user.emailVerifiedAt,null);for(const extra of [{capabilities:['users.manage']},{emailVerifiedAt:new Date().toISOString()},{password:'admin-chosen-password'},{createdBy:'forged'}])await assert.rejects(accounts.create(admin,{...profile('forged'),...extra}),e=>e.name==='ZodError');});
test('users: setup code has 256-bit entropy, hashes only at rest, expires in 24h and is not retrievable/audited',async()=>{const r=await create();assert.match(r.setup.token,/^[A-Za-z0-9_-]{43}$/);const t=(await pool.query('SELECT * FROM wahi_v2.user_setup_tokens WHERE user_id=$1',[r.user.id])).rows[0];assert.notEqual(t.token_hash,r.setup.token);assert.equal(t.expires_at-t.issued_at,86400000);const detail=await accounts.detail(admin,r.user.id);const list=await accounts.list(admin);assert.ok(!JSON.stringify({detail,list}).includes(r.setup.token));assert.ok(!JSON.stringify({detail,list}).includes(t.token_hash));assert.ok(!JSON.stringify(detail).includes('password_hash'));assert.equal(await session('sarah'),null);});
test('users: own password establishment consumes token once and never creates an authenticated session',async()=>{const r=await create();assert.equal((await accounts.establish({token:r.setup.token,password})).established,true);assert.ok(await session('sarah'));await assert.rejects(accounts.establish({token:r.setup.token,password:nextPassword}),e=>e.code==='invalid_setup');assert.ok(await verify(await accounts.findLogin('sarah'),password));const detail=await accounts.detail(admin,r.user.id);assert.equal(detail.pendingSetup,null);assert.ok(detail.audit.some(a=>a.event==='password_established'));assert.ok(!JSON.stringify(detail).includes(password));});
test('users: expired, fabricated, used and disabled tokens have neutral rejection',async()=>{const r=await create();await pool.query("UPDATE wahi_v2.user_setup_tokens SET expires_at=CURRENT_TIMESTAMP-interval '1 second' WHERE user_id=$1",[r.user.id]);for(const token of [r.setup.token,crypto.randomBytes(32).toString('base64url')])await assert.rejects(accounts.establish({token,password}),e=>e.code==='invalid_setup');const other=await create('other');await edit(other.user,{status:'disabled'});await assert.rejects(accounts.establish({token:other.setup.token,password}),e=>e.code==='invalid_setup');});
test('users: new issuance supersedes every previous code',async()=>{const r=await create();const next=await action(r.user,'issue-setup');await assert.rejects(accounts.establish({token:r.setup.token,password}),e=>e.code==='invalid_setup');await accounts.establish({token:next.setup.token,password});assert.ok(await session('sarah'));});
test('users: concurrent token consumption has one winner',async()=>{const r=await create();const outcomes=await Promise.allSettled([accounts.establish({token:r.setup.token,password}),accounts.establish({token:r.setup.token,password:nextPassword})]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);});
test('users: reset revokes all same-user sessions including sessions created after issuance; other account retained',async()=>{const u=await established(),b=await established('other');const a1=await session(u.username),a2=await session(u.username),b1=await session(b.username);const r=await action(u,'issue-setup');assert.equal(await store.get(a1),null);assert.equal(await store.get(a2),null);const between=await session(u.username);await accounts.establish({token:r.setup.token,password:nextPassword});assert.equal(await store.get(between),null);assert.equal(await session(u.username,password),null);assert.ok(await session(u.username,nextPassword));assert.ok(await store.get(b1));});
test('users: Manager downgrade and Staff elevation both revoke prior sessions',async()=>{const u=await established('manager','MANAGER');const old=await session(u.username);await edit(u,{role:'STAFF'});assert.equal(await store.get(old),null);const staff=await session(u.username);assert.equal((await store.get(staff)).user.role,'STAFF');await edit(u,{role:'MANAGER'});assert.equal(await store.get(staff),null);assert.equal((await store.get(await session(u.username))).user.role,'MANAGER');});
test('users: Admin downgrade revokes prior administrative session',async()=>{const u=await established('second-admin','ADMIN');const old=await session(u.username);await edit(u,{role:'STAFF'});assert.equal(await store.get(old),null);await assert.rejects(accounts.list({id:u.id,role:'ADMIN'}),e=>e.code==='forbidden');});
test('users: disable prevents login and invalidates sessions; enable cannot resurrect them',async()=>{const u=await established(),old=await session(u.username);await edit(u,{status:'disabled'});assert.equal(await session(u.username),null);assert.equal(await store.get(old),null);await edit(u,{status:'active'});assert.equal(await store.get(old),null);assert.ok(await session(u.username));assert.equal((await accounts.detail(admin,u.id)).user.id,u.id);});
test('users: explicit revocation is individual and records security event',async()=>{const u=await established(),b=await established('other');const a1=await session(u.username),a2=await session(u.username),b1=await session(b.username);await action(u,'revoke');assert.equal(await store.get(a1),null);assert.equal(await store.get(a2),null);assert.ok(await store.get(b1));assert.ok((await accounts.detail(admin,u.id)).audit.some(a=>a.event==='sessions_revoked'&&a.details.count===2));});
test('users: last usable Admin protected; pending Admin does not count; own demotion/disable prohibited',async()=>{await create('pending-admin','ADMIN');const owner=(await accounts.detail(admin,admin.id)).user;await assert.rejects(edit(owner,{status:'disabled'}),e=>e.code==='last_admin');await assert.rejects(edit(owner,{role:'STAFF'}),e=>e.code==='last_admin');await established('second-admin','ADMIN');await assert.rejects(edit(owner,{status:'disabled'}),e=>e.code==='self_access_change');await assert.rejects(edit(owner,{role:'MANAGER'}),e=>e.code==='self_access_change');});
test('users: database prevents destructive deletion and security audit mutation',async()=>{const u=await established();await assert.rejects(pool.query('DELETE FROM wahi_v2.users WHERE id=$1',[u.id]));await assert.rejects(pool.query('DELETE FROM wahi_v2.user_security_audit WHERE user_id=$1',[u.id]));});
test('users: disabled creation issues no useless code; enabling allows explicit issue',async()=>{const r=await create('disabled','STAFF','disabled');assert.equal(r.setup,null);await assert.rejects(action(r.user,'issue-setup'),e=>e.code==='invalid_state');await edit(r.user,{status:'active'});const code=await action(r.user,'issue-setup');await accounts.establish({token:code.setup.token,password});assert.ok(await session('disabled'));});
test('users: stale profile version cannot overwrite concurrent access changes',async()=>{const r=await create();await edit(r.user,{role:'MANAGER'});await assert.rejects(accounts.mutate(admin,'update',{id:r.user.id,expectedVersion:r.user.version,...profile()}),e=>e.code==='revision_conflict');});
test('users: required audit failure rolls back creation, token issuance, access changes and revocation',async()=>{const u=await established(),old=await session(u.username);await pool.query("CREATE FUNCTION wahi_v2.reject_user_audit_test() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit failure'; END; $$; CREATE TRIGGER reject_user_audit_test BEFORE INSERT ON wahi_v2.user_security_audit FOR EACH ROW EXECUTE FUNCTION wahi_v2.reject_user_audit_test()");try{await assert.rejects(create('failure'));await assert.rejects(edit(u,{status:'disabled'}));await assert.rejects(action(u,'revoke'));await assert.rejects(action(u,'issue-setup'));assert.ok(await store.get(old));assert.equal((await accounts.list(admin)).users.some(r=>r.username==='failure'),false);}finally{await pool.query('DROP TRIGGER reject_user_audit_test ON wahi_v2.user_security_audit; DROP FUNCTION wahi_v2.reject_user_audit_test()');}});
test('users: password reset audit failure rolls back password/token/session changes',async()=>{const u=await established(),r=await action(u,'issue-setup'),old=await session(u.username);await pool.query("CREATE FUNCTION wahi_v2.reject_reset_audit_test() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit failure'; END; $$; CREATE TRIGGER reject_reset_audit_test BEFORE INSERT ON wahi_v2.user_security_audit FOR EACH ROW EXECUTE FUNCTION wahi_v2.reject_reset_audit_test()");try{await assert.rejects(accounts.establish({token:r.setup.token,password:nextPassword}));assert.ok(await store.get(old));assert.ok(await session(u.username,password));}finally{await pool.query('DROP TRIGGER reject_reset_audit_test ON wahi_v2.user_security_audit; DROP FUNCTION wahi_v2.reject_reset_audit_test()');}await accounts.establish({token:r.setup.token,password:nextPassword});assert.equal(await store.get(old),null);});
test('users: login authenticated before downgrade cannot insert stale session afterward',async()=>{const u=await established(),candidate=await accounts.findLogin(u.username);await edit(u,{role:'MANAGER'});await assert.rejects(store.set(crypto.randomUUID(),{user:candidate,csrf:'test',expires:Date.now()+60000}),e=>e.code==='unauthenticated');});

async function httpStart(){server=createReviewServer({service:new DomainService(new MemoryRepository()),users:[adminCredentials],accounts,sessionStore:store,runtime:{hosted:true,origin:'https://wahi-reporting-system.onrender.com',environment:'production'}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=server.address().port;}
async function request(url,{body,auth,headers={}}={}){return new Promise((resolve,reject)=>{const q=http.request({hostname:'127.0.0.1',port:base,path:url,method:body?'POST':'GET',headers:{Host:'wahi-reporting-system.onrender.com',Origin:'https://wahi-reporting-system.onrender.com','Content-Type':'application/json',...(auth?{Cookie:auth.cookie,...(auth.csrf?{'X-CSRF-Token':auth.csrf}:{})}:{}),...headers}},r=>{let s='';r.on('data',d=>s+=d);r.on('end',()=>resolve({status:r.statusCode,data:JSON.parse(s),cookie:r.headers['set-cookie']?.[0].split(';')[0]}));});q.on('error',reject);q.end(body?JSON.stringify(body):undefined);});}
async function loginHttp(username,pass=password){const r=await request('/api/login',{body:{username,password:pass}});assert.equal(r.status,200);const me=await request('/api/me',{auth:{cookie:r.cookie}});return {cookie:r.cookie,csrf:me.data.csrf};}
test('users HTTP: real lower-role sessions cannot list/create/edit/revoke/issue, including forged role headers',async()=>{await httpStart();try{for(const role of ['STAFF','LEAD','MANAGER']){const u=await established(role.toLowerCase(),role),auth=await loginHttp(u.username);for(const endpoint of ['','/detail?id='+admin.id])assert.equal((await request('/api/admin/users'+endpoint,{auth,headers:{'X-Role':'ADMIN'}})).status,403);for(const endpoint of ['create','update','revoke','issue-setup'])assert.equal((await request('/api/admin/users/'+endpoint,{auth,body:{role:'ADMIN',actorId:admin.id}})).status,403);}assert.equal((await request('/api/admin/users')).status,401);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));server=null;}});
test('users HTTP: CSRF, strict payloads, neutral setup errors, secret-free detail and successful setup login',async()=>{await httpStart();try{const auth=await loginHttp(' OWNER ');assert.equal((await request('/api/admin/users/create',{auth,body:profile(),headers:{'X-CSRF-Token':'wrong'}})).status,403);assert.equal((await request('/api/admin/users/create',{auth,body:{...profile(),capabilities:['users.manage']}})).status,400);const r=await request('/api/admin/users/create',{auth,body:profile()});assert.equal(r.status,200);const token=r.data.setup.token;const detail=await request('/api/admin/users/detail?id='+r.data.user.id,{auth});assert.ok(!JSON.stringify(detail).includes(token));assert.equal((await request('/api/account/setup',{body:{token,password},headers:{Origin:'https://attacker.invalid'}})).status,403);assert.equal((await request('/api/account/setup',{body:{token,password}})).status,200);assert.equal((await request('/api/account/setup',{body:{token,password}})).status,400);const user=await loginHttp('SARAH');assert.equal((await request('/api/admin/users',{auth:user})).status,403);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));server=null;}});
test('users table: search matches name, username, email and access; filters combine',()=>{const {selectUsers}=require('../review/public/users-ui');const rows=[{name:'Sarah',username:'sarah',email:'sarah@example.com',role:'MANAGER',status:'active'},{name:'Jordan',username:'jordan',email:null,role:'STAFF',status:'disabled'}];assert.equal(selectUsers(rows,{search:'EXAMPLE',role:'MANAGER',status:'active'}).length,1);assert.equal(selectUsers(rows,{search:'Sarah',status:'disabled'}).length,0);assert.equal(selectUsers(rows,{search:'STAFF'})[0].username,'jordan');assert.equal(selectUsers(rows,{search:'sarah'})[0].name,'Sarah');});
test('users table: sensible sorting, direction and missing email/login values',()=>{const {selectUsers}=require('../review/public/users-ui');const rows=[{name:'Zed',username:'zed',role:'STAFF',email:null,lastLoginAt:null},{name:'Amy',username:'amy',role:'STAFF',email:'amy@example.com',lastLoginAt:'2026-01-01'}];assert.equal(selectUsers(rows)[0].username,'amy');assert.equal(selectUsers(rows,{direction:'desc'})[0].username,'zed');assert.equal(selectUsers(rows,{sort:'lastLoginAt',direction:'desc'})[0].username,'amy');assert.equal(selectUsers(rows,{sort:'email'})[0].username,'zed');});
test('users UI: returning from public setup restores an already-authenticated workspace',async()=>{const vm=require('node:vm'),read=require('node:fs').readFileSync;const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,innerHTML:'',textContent:'',style:{},addEventListener(){}});return nodes.get(id);};const context=vm.createContext({URLSearchParams,document:{getElementById:node},window:{addEventListener(){}},location:{hash:'#account-setup'},console,setTimeout(){},module:{exports:{}}});vm.runInContext(read(path.join(__dirname,'../review/public/app.js'),'utf8'),context);vm.runInContext(read(path.join(__dirname,'../review/public/users-ui.js'),'utf8'),context);vm.runInContext("me={id:'owner',capabilities:[]};shellState={drawer:false};renderShell=()=>{};shellHome=()=>{}",context);await vm.runInContext('route()',context);assert.equal(node('workspace').hidden,true);assert.equal(node('account-setup').hidden,false);context.location.hash='#home';await vm.runInContext('route()',context);assert.equal(node('workspace').hidden,false);assert.equal(node('login').hidden,true);assert.equal(node('account-setup').hidden,true);});
