'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {build}=require('../import/importer'),{DomainService}=require('../service'),{MemoryRepository}=require('../repository/memory'),{management}=require('../review/management'),{itemRecord}=require('../review/items'),{currentVendors}=require('../review/vendors'),table=require('../review/public/table-model');
const at='2026-09-18T20:40:26.000Z',actor={id:'test',role:'ADMIN'},provenance={kind:'manual',reference:'vendor regression'};
async function setup(){const r=await build(require('./fixtures/wahi-source.json'),{activationAt:at});return {s:r.state,service:new DomainService(new MemoryRepository(r.state),{clock:()=>at})};}
test('vendors: imported purchasing relationships appear in management and detail',async()=>{const {s,service}=await setup(),p=s.purchaseOptions.find(p=>p.supplierId),vendor=s.suppliers.find(v=>v.id===p.supplierId),view=await management(service,actor),detail=await itemRecord(service,actor,p.ingredientId);assert.ok(view.items.find(i=>i.id===p.ingredientId).vendors.some(v=>v.id===vendor.id&&v.name===vendor.name));assert.equal(detail.packages.find(x=>x.id===p.id).vendor.id,vendor.id);});
const rows=[{name:'One',active:true,vendors:[{id:'z',name:'Zulu'},{id:'a',name:'Alpha'}]},{name:'Two',active:true,vendors:[{id:'b',name:'Bravo'}]},{name:'Three',active:true,vendors:[]}];
test('vendors: sorting uses all displayed vendor names with stable item tie-break',()=>{assert.deepEqual(table.select(rows,{sort:'vendor'}).map(r=>r.name),['Three','One','Two']);assert.deepEqual(table.select(rows,{sort:'vendor',direction:'desc'}).map(r=>r.name),['Two','One','Three']);});
test('vendors: filtering matches any associated vendor and no-vendor',()=>{for(const id of ['a','z'])assert.deepEqual(table.select(rows,{vendor:id}).map(r=>r.name),['One']);assert.deepEqual(table.select(rows,{vendor:'__none'}).map(r=>r.name),['Three']);});
test('vendors: search is case insensitive and combines with vendor filter',()=>{assert.deepEqual(table.select(rows,{query:'ZULU'}).map(r=>r.name),['One']);assert.equal(table.select(rows,{query:'Zulu',vendor:'b'}).length,0);});
test('vendors: multiple active sources retain distinct IDs, selection for costing does not discard alternatives',async()=>{const {s,service}=await setup(),p=s.purchaseOptions.find(p=>p.supplierId),v=await service.execute(actor,'createSupplier',{name:'Additional source',provenance});await service.execute(actor,'createPurchaseOption',{ingredientId:p.ingredientId,supplierId:v.id,label:'Alternate package',contentQuantity:'1',contentUnit:'each',provenance});const projected=currentVendors(await service.repository.read(),p.ingredientId,at);assert.equal(projected.length,2);assert.ok(projected.some(x=>x.id===p.supplierId));assert.ok(projected.some(x=>x.id===v.id));});
test('vendors: absent vendor remains empty without invented fallback',async()=>{const {s,service}=await setup(),i=s.ingredients.find(i=>i.name==='Egg Roll Wraps');assert.deepEqual((await management(service,actor)).items.find(x=>x.id===i.id).vendors,[]);});
test('vendors: inactive and future-only sources excluded; dated source eligibility respects known-at',async()=>{const {s}=await setup(),p=s.purchaseOptions.find(p=>p.supplierId),price=s.prices.find(x=>x.purchaseOptionId===p.id);assert.equal(currentVendors(s,p.ingredientId,at).length,1);p.active=false;assert.equal(currentVendors(s,p.ingredientId,at).length,0);p.active=true;for(const b of s.bases.filter(b=>b.purchaseOptionId===p.id))b.effectiveAt='2026-10-01T00:00:00.000Z';price.effectiveAt='2026-10-01T00:00:00.000Z';assert.equal(currentVendors(s,p.ingredientId,at).length,0);assert.equal(currentVendors(s,p.ingredientId,'2026-10-02T00:00:00.000Z').length,1);assert.equal(currentVendors(s,p.ingredientId,'2026-10-02T00:00:00.000Z','2026-01-01T00:00:00.000Z').length,0);});
test('vendors: Staff and Lead do not receive purchasing vendor projections',async()=>{const {s,service}=await setup();for(const role of ['STAFF','LEAD']){const a={id:'test',role};assert.ok((await management(service,a)).items.every(i=>i.vendors===undefined));assert.equal((await itemRecord(service,a,s.ingredients[0].id)).packages,undefined);}});
test('vendors: supplier identity, filter matches and projection persist across repository reload',async()=>{const {service}=await setup(),before=await management(service,actor),state=await service.repository.read(),reload=new DomainService(new MemoryRepository(JSON.parse(JSON.stringify(state))),{clock:()=>at});assert.deepEqual((await management(reload,actor)).items.map(i=>i.vendors),before.items.map(i=>i.vendors));});
test('vendors: imported same-name supplier identities remain distinct selectable filters',()=>{const options=table.vendorOptions([{vendors:[{id:'11111111-a',name:'Amazon'},{id:'22222222-b',name:'Amazon'}]}]);assert.equal(options.length,2);assert.notEqual(options[0][1],options[1][1]);assert.deepEqual(options.map(x=>x[0]),['11111111-a','22222222-b']);});
