'use strict';
const crypto=require('node:crypto'),{latest}=require('../domain/history');
const normalize=s=>s.normalize('NFKC').trim().toLowerCase().replace(/[‘’ʼ]/g,"'").replace(/[‐‑‒–—]/g,'-').replace(/\s+/g,' ');
const loose=s=>normalize(s).normalize('NFD').replace(/\p{M}/gu,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
function distance(a,b){let row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(next[j-1]+1,row[j]+1,row[j-1]+(a[i-1]===b[j-1]?0:1));row=next;}return row[b.length];}
function plausible(a,b){a=loose(a);b=loose(b);if(!a||!b)return null;if(a===b)return 'Name matches after accent/punctuation simplification';const x=a.split(' '),y=b.split(' '),common=x.filter(t=>y.includes(t)).length;if(Math.min(x.length,y.length)>=2&&common===Math.min(x.length,y.length)&&Math.max(x.length,y.length)<=Math.min(x.length,y.length)+2)return 'Shared name words; extra words may change the portion or product';if(Math.min(a.length,b.length)>=5&&Math.max(a.length,b.length)<=120&&distance(a,b)<=Math.floor(Math.max(a.length,b.length)*0.2))return 'Similar spelling';return null;}
function classify(item,targets){const exact=targets.filter(t=>normalize(t.name)===normalize(item.name));if(exact.length)return {quality:exact.length===1?'EXACT':'AMBIGUOUS',candidates:exact.map(t=>({...t,why:'Same normalized name'}))};const suggested=targets.flatMap(t=>{const why=plausible(item.name,t.name);return why?[{...t,why}]:[];});return {quality:suggested.length>1?'AMBIGUOUS':suggested.length?'SUGGESTED':'NONE',candidates:suggested};}
async function targets(c,now){const menu=await c.query('SELECT id,name FROM wahi_v2.menu_items WHERE active ORDER BY name,id'),recipe=await c.query('SELECT id,name FROM wahi_v2.recipes WHERE active ORDER BY name,id'),mappings=await c.query('SELECT * FROM wahi_v2.menu_mappings ORDER BY menu_item_id,effective_at,recorded_at,id');const revisions=mappings.rows.map(r=>({...r,effectiveAt:r.effective_at?.toISOString()||null,recordedAt:r.recorded_at.toISOString(),supersedesId:r.supersedes_id}));const options=[...menu.rows.map(m=>{const p=latest(revisions.filter(r=>r.menu_item_id===m.id),now,now);return {key:'menu:'+m.id,type:'menu',id:m.id,name:m.name,portion:p?{recipeId:p.recipe_id,quantity:p.quantity,unit:p.unit}:null};}),...recipe.rows.map(r=>({key:'recipe:'+r.id,type:'recipe',...r,portion:null}))];return {options,fingerprint:hash(options)};}
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
async function assistance(c,items,targetSet){const missing=items.filter(i=>i.state==='unmapped'),ids=missing.map(i=>i.id);const stored=new Map((await c.query('SELECT * FROM wahi_v2.cogs_candidates WHERE item_id=ANY($1::text[])',[ids])).rows.map(r=>[r.item_id,r]));let generated=0;const writes=[];for(const item of missing){const fingerprint=hash([item.name,targetSet.fingerprint,'v1']),cached=stored.get(item.id);item.assistance=cached?.fingerprint===fingerprint?cached.payload:classify(item,targetSet.options);if(cached?.fingerprint!==fingerprint){generated++;writes.push({item_id:item.id,fingerprint,payload:item.assistance});}item.candidateFingerprint=fingerprint;item.bulkEligible=item.assistance.quality==='EXACT'&&item.assistance.candidates[0].type==='menu'&&!!item.assistance.candidates[0].portion;}
if(writes.length)await c.query(`INSERT INTO wahi_v2.cogs_candidates(item_id,fingerprint,payload) SELECT item_id,fingerprint,payload FROM jsonb_to_recordset($1::jsonb) x(item_id text,fingerprint text,payload jsonb) ON CONFLICT(item_id) DO UPDATE SET fingerprint=EXCLUDED.fingerprint,payload=EXCLUDED.payload,generated_at=CURRENT_TIMESTAMP`,[JSON.stringify(writes)]);return {generated,reused:missing.length-generated};}
module.exports={normalize,plausible,classify,targets,assistance,hash};
