'use strict';
const {z}=require('zod'),crypto=require('crypto'),{authorize}=require('../auth'),{Exact:E}=require('../domain/exact'),{fail}=require('../labor/model'),{targets}=require('./candidates'),C=require('./composite'),{pack,encode}=require('./cost');
const positive=z.string().max(40).refine(s=>{try{return E.of(s).positive()&&E.of('1000000').sub(s).nonnegative();}catch{return false;}});
const definition=z.object({name:z.string().trim().min(1).max(100),pieceName:z.string().trim().min(1).max(40),expectedPieces:positive,components:z.array(z.object({key:z.string().min(1).max(100),name:z.string().trim().min(1).max(100),recipeId:z.string().uuid(),piecesPerExecution:positive}).strict()).min(1).max(100),parents:z.array(z.object({itemId:z.string().min(1).max(100),expectedVersion:z.number().int().nonnegative(),groupPath:z.array(z.string().min(1).max(100)).min(1).max(13),options:z.array(z.object({optionId:z.string().uuid(),componentKey:z.string().min(1).max(100)}).strict()).max(200)}).strict()).min(1).max(100)}).strict();
const inputSchema=z.object({id:z.string().uuid().nullable().default(null),expectedVersion:z.number().int().nonnegative(),confirmed:z.boolean().default(false),definition,period:z.object({start:z.string(),end:z.string()}).strict()}).strict();
function unique(xs){if(new Set(xs).size!==xs.length)throw fail('composite_duplicate_choice');}
async function observations(c,ids){const rows=(await c.query('SELECT source FROM wahi_v2.sales_facts WHERE present AND item_id=ANY($1::text[])',[ids])).rows;const out=new Map(ids.map(id=>[id,new Map()]));for(const {source:f}of rows){for(const [k,g]of C.groups(f.modifiers)){const bag=out.get(f.itemId);if(!bag.has(k))bag.set(k,{path:g.path,options:new Set()});for(const o of g.options)if(o.itemId)bag.get(k).options.add(o.itemId);}}return {rows:rows.map(r=>r.source),groups:out};}
class CompositeReview{
 constructor(cogs){this.cogs=cogs;this.pool=cogs.pool;}
 async catalog(actor,input){authorize(actor,'reporting.configure');const ids=String(input.ids||input.id||'').split(',').filter(Boolean);if(!ids.length||ids.length>100)throw fail('invalid_request');const c=await this.pool.connect();try{const observed=await observations(c,ids),definitions=(await c.query('SELECT * FROM wahi_v2.cogs_composites ORDER BY name,id')).rows;return {definitions,parents:ids.map(id=>({itemId:id,context:C.hints.parents[id]?.context||'',groups:[...observed.groups.get(id).values()].map(g=>{const hint=C.hints.groups[g.path.at(-1)];return {path:g.path,recommended:!!C.hints.parents[id]?.groups.includes(g.path.at(-1)),name:hint?.name||'Observed choice group',options:[...g.options].sort().map(optionId=>({optionId,name:hint?.options[optionId]?.name||'Unlabelled Toast option',suggestedKey:hint?.options[optionId]?.suggestedKey||optionId}))};})}))};}finally{c.release();}}
 async validate(c,actor,input){const d=inputSchema.parse(input);await this.cogs.review.period(d.period);unique(d.definition.components.map(x=>x.key));unique(d.definition.parents.map(x=>x.itemId));const eligible=await targets(c,new Date(this.cogs.clock()).toISOString());for(const x of d.definition.components)if(!eligible.options.some(r=>r.id===x.recipeId))throw fail('ineligible_mapping_target');const observed=await observations(c,d.definition.parents.map(p=>p.itemId));for(const p of d.definition.parents){if(!(await c.query('SELECT id FROM wahi_v2.sales_items WHERE id=$1',[p.itemId])).rowCount)throw fail('not_found');const g=observed.groups.get(p.itemId).get(C.key(p.groupPath));if(!g)throw fail('composite_group_invalid');unique(p.options.map(x=>x.optionId));for(const o of p.options)if(!g.options.has(o.optionId)||!d.definition.components.some(c=>c.key===o.componentKey))throw fail('composite_option_invalid');if(!p.options.length)throw fail('composite_option_invalid');}return {d,facts:observed.rows.filter(f=>!f.reason&&f.businessDate>=d.period.start&&f.businessDate<=d.period.end)};}
 async preview(actor,input){authorize(actor,'reporting.configure');const c=await this.pool.connect();try{await c.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const {d,facts}=await this.validate(c,actor,input),stats={historicalResolutions:0,currentResolutions:0},runner=await C.evaluator(c,d.definition,new Date(this.cogs.clock()).toISOString(),stats),out=C.aggregate(facts,runner),{presentation}=require('./service');await c.query('COMMIT');return {preview:true,saved:false,...presentation(out),composition:C.describe(out.compositions),provenance:out.compositions,parents:d.definition.parents.map(p=>{const rows=facts.filter(f=>f.itemId===p.itemId),a=C.aggregate(rows,runner);return {itemId:p.itemId,...presentation(a),composition:C.describe(a.compositions)};}),stats};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async save(actor,input){authorize(actor,'reporting.configure');return this.cogs.locked(async c=>{await c.query('BEGIN');try{await c.query('SELECT pg_advisory_xact_lock(781902641)');const {checkAdmin,writePolicy}=require('./mapping');await checkAdmin(c,actor);const {d}=await this.validate(c,actor,input),id=d.id||crypto.randomUUID(),old=(await c.query('SELECT * FROM wahi_v2.cogs_composites WHERE id=$1 FOR UPDATE',[id])).rows[0];if((old?.version||0)!==d.expectedVersion||d.id&&!old)throw fail('revision_conflict');if(old&&!d.confirmed)throw fail('mapping_confirmation_required');const previousParents=(await c.query('SELECT * FROM wahi_v2.cogs_mappings WHERE composite_id=$1',[id])).rows;await c.query('INSERT INTO wahi_v2.cogs_composites(id,name,version,definition) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,version=EXCLUDED.version,definition=EXCLUDED.definition,updated_at=CURRENT_TIMESTAMP',[id,d.definition.name,d.expectedVersion+1,d.definition]);
 for(const p of previousParents)if(!d.definition.parents.some(x=>x.itemId===p.item_id))await writePolicy(c,actor,{itemId:p.item_id,state:'unmapped',expectedVersion:p.version,mode:'execution',confirmed:true,reason:'Detached from composite',keepDefinition:true});
 for(const p of d.definition.parents)await writePolicy(c,actor,{itemId:p.itemId,state:'mapped',expectedVersion:p.expectedVersion,mode:'composite',compositeId:id,confirmed:d.confirmed,reason:'Composite mapping',keepDefinition:true});
 await c.query('INSERT INTO wahi_v2.cogs_composite_audit(id,composite_id,actor_id,previous,next) VALUES($1,$2,$3,$4,$5)',[crypto.randomUUID(),id,actor.id,old||null,{action:old?'composite_changed':'composite_created',version:d.expectedVersion+1,definition:d.definition}]);await c.query('COMMIT');return {saved:true,id,version:d.expectedVersion+1};}catch(e){await c.query('ROLLBACK');throw e;}});}
}
module.exports={CompositeReview,observations,definition};
