'use strict';
const {z}=require('zod'),crypto=require('node:crypto'),{authorize}=require('../auth'),{Exact:E}=require('../domain/exact'),{date,addDays,fail}=require('../labor/model'),candidates=require('./candidates');
const itemId=z.string().min(1).max(100),decimal=x=>E.of(x).decimal(20).replace(/\.?0+$/,''),percentage=(n,d)=>E.of(d).positive()?E.of(n).div(d).mul('100').decimal(2):null;
const policy=z.object({itemId,state:z.enum(['mapped','excluded','unmapped']),expectedVersion:z.number().int().nonnegative(),menuItemId:z.string().uuid().nullable(),recipeId:z.string().uuid().nullable(),quantity:z.string().nullable(),unit:z.string().max(40).nullable(),reason:z.string().trim().max(300).default(''),confirmed:z.boolean().default(false),candidateFingerprint:z.string().optional()}).strict();
async function checkAdmin(c,actor){const user=(await c.query('SELECT role,status FROM wahi_v2.users WHERE id=$1 FOR SHARE',[actor.id])).rows[0];if(user?.role!=='ADMIN'||user.status!=='active')throw fail('forbidden');}
async function writePolicy(c,actor,d,bulkId=null){
 const item=(await c.query('SELECT id,name FROM wahi_v2.sales_items WHERE id=$1',[d.itemId])).rows[0];if(!item)throw fail('not_found');
 const old=(await c.query('SELECT * FROM wahi_v2.cogs_mappings WHERE item_id=$1 FOR UPDATE',[d.itemId])).rows[0];if((old?.version||0)!==d.expectedVersion)throw fail('revision_conflict');
 if(old&&old.state!=='unmapped'&&!d.confirmed)throw fail('mapping_confirmation_required');
 if(d.state==='mapped'){
  if(!(!!d.menuItemId!==!!d.recipeId))throw fail('invalid_request');
  const table=d.menuItemId?'menu_items':'recipes';if(!(await c.query(`SELECT id FROM wahi_v2.${table} WHERE id=$1 AND active`,[d.menuItemId||d.recipeId])).rowCount)throw fail('inactive_reference');
  if(d.recipeId&&(!d.quantity||!E.of(d.quantity).positive()||!d.unit?.trim()))throw fail('invalid_request');
 }
 const clean={...d,menuItemId:d.state==='mapped'?d.menuItemId:null,recipeId:d.state==='mapped'?d.recipeId:null,quantity:d.state==='mapped'&&d.recipeId?d.quantity:null,unit:d.state==='mapped'&&d.recipeId?d.unit:null};
 const action=d.state==='excluded'?'ignore_enabled':d.state==='unmapped'?(old?.state==='excluded'?'ignore_disabled':'mapping_removed'):(old?.state==='excluded'?'ignore_replaced_by_mapping':old?.state==='mapped'?'mapping_changed':'mapping_created');
 await c.query(`INSERT INTO wahi_v2.cogs_mappings(item_id,state,menu_item_id,recipe_id,quantity,unit,version,provenance,reason) VALUES($1,$2,$3,$4,$5,$6,$7,'admin',$8) ON CONFLICT(item_id) DO UPDATE SET state=EXCLUDED.state,menu_item_id=EXCLUDED.menu_item_id,recipe_id=EXCLUDED.recipe_id,quantity=EXCLUDED.quantity,unit=EXCLUDED.unit,version=EXCLUDED.version,provenance='admin',reason=EXCLUDED.reason,updated_at=CURRENT_TIMESTAMP`,[clean.itemId,clean.state,clean.menuItemId,clean.recipeId,clean.quantity,clean.unit,d.expectedVersion+1,clean.reason]);
 const invalidated=await c.query('UPDATE wahi_v2.cogs_knowledge SET dirty=TRUE WHERE item_id=$1',[d.itemId]);
 await c.query('INSERT INTO wahi_v2.cogs_mapping_audit(id,item_id,actor_id,previous,next) VALUES($1,$2,$3,$4,$5)',[crypto.randomUUID(),d.itemId,actor.id,old||null,{...clean,action,bulkId,toastName:item.name}]);
 return {saved:true,itemId:d.itemId,version:d.expectedVersion+1,invalidated:invalidated.rowCount,action};
}
class MappingReview{
 constructor(cogs){this.cogs=cogs;this.pool=cogs.pool;}
 async period(input={}){const config=await this.cogs.settings(),start=input.start||addDays(config.today,-27),end=input.end||config.today;date(start);date(end);if(start>end||end>config.today)throw fail('invalid_request');return {start,end};}
 async badge(actor){authorize(actor,'reporting.configure');const d=await this.period();const r=await this.pool.query(`SELECT count(DISTINCT s.item_id)::int count FROM wahi_v2.sales_item_days s LEFT JOIN wahi_v2.cogs_mappings m ON m.item_id=s.item_id WHERE s.business_date BETWEEN $1 AND $2 AND s.quantity>0 AND COALESCE(m.state,'unmapped')='unmapped'`,[d.start,d.end]);return {count:r.rows[0].count,period:d};}
 async list(actor,input={}){authorize(actor,'reporting.configure');const started=performance.now(),d=await this.period(input),now=new Date(this.cogs.clock()).toISOString();const c=await this.pool.connect();try{
 const items=(await c.query(`SELECT i.id,i.name,i.group_id,COALESCE(m.state,'unmapped') state,COALESCE(m.version,0) version,m.menu_item_id,m.recipe_id,m.quantity::text portion_quantity,m.unit,COALESCE(m.reason,'') reason,m.provenance,COALESCE(s.quantity,0)::text quantity,CASE WHEN s.item_id IS NULL THEN '0' ELSE s.net_sales::text END net_sales,COALESCE(s.selections,0)::int selections FROM wahi_v2.sales_items i LEFT JOIN wahi_v2.cogs_mappings m ON m.item_id=i.id LEFT JOIN (SELECT item_id,sum(quantity) quantity,CASE WHEN bool_and(net_sales IS NOT NULL) THEN sum(net_sales) END net_sales,sum(selection_count) selections FROM wahi_v2.sales_item_days WHERE business_date BETWEEN $1 AND $2 GROUP BY item_id) s ON s.item_id=i.id ORDER BY COALESCE(s.quantity,0) DESC,i.name,i.id`,[d.start,d.end])).rows;
 const targetSet=await candidates.targets(c,now),cache=await candidates.assistance(c,items,targetSet);
 const counts={unmapped:0,mapped:0,excluded:0},recent={unmapped:0,mapped:0,excluded:0},qualities={EXACT:0,SUGGESTED:0,AMBIGUOUS:0,NONE:0},qty={unmapped:E.of('0'),mapped:E.of('0'),excluded:E.of('0')},net={unmapped:E.of('0'),mapped:E.of('0'),excluded:E.of('0')};let known=true;
 for(const i of items){counts[i.state]++;if(E.of(i.quantity).positive()){recent[i.state]++;if(i.assistance)qualities[i.assistance.quality]++;}qty[i.state]=qty[i.state].add(i.quantity);if(i.net_sales===null)known=false;else net[i.state]=net[i.state].add(i.net_sales);i.target=targetSet.options.find(t=>t.key===(i.menu_item_id?'menu:'+i.menu_item_id:'recipe:'+i.recipe_id))||null;if(i.state==='mapped'&&!i.target){const table=i.menu_item_id?'menu_items':'recipes';const r=(await c.query(`SELECT id,name FROM wahi_v2.${table} WHERE id=$1`,[i.menu_item_id||i.recipe_id])).rows[0];i.target=r?{...r,type:i.menu_item_id?'menu':'recipe',key:(i.menu_item_id?'menu:':'recipe:')+r.id,inactive:true}:null;}}
 const total=qty.mapped.add(qty.unmapped).add(qty.excluded),sales=net.mapped.add(net.unmapped).add(net.excluded);
 const bulkPreview=rows=>{const eligible=rows.filter(i=>i.bulkEligible).slice(0,500),amount=eligible.reduce((a,i)=>a.add(i.quantity),E.of('0')),sales=eligible.reduce((a,i)=>a.add(i.net_sales||'0'),E.of('0'));return {entries:eligible.map(i=>({itemId:i.id,expectedVersion:i.version,candidateFingerprint:i.candidateFingerprint,targetKey:i.assistance.candidates[0].key})),quantity:decimal(amount),netSales:eligible.every(i=>i.net_sales!==null)?sales.decimal(12):null};};
 return {bulk:{recent:bulkPreview(items.filter(i=>E.of(i.quantity).positive())),all:bulkPreview(items)},period:d,items,targets:targetSet.options,counts,recentCounts:recent,candidateCounts:qualities,coverage:{quantity:decimal(total),mappedQuantity:decimal(qty.mapped),needsMappingQuantity:decimal(qty.unmapped),ignoredQuantity:decimal(qty.excluded),unitsPercent:percentage(qty.mapped,total),netSales:known?sales.decimal(12):null,netSalesPercent:known?percentage(net.mapped,sales):null},stats:{...cache,durationMs:performance.now()-started}};
 }finally{c.release();}}
 async save(actor,input){authorize(actor,'reporting.configure');const d=policy.parse(input);return this.cogs.locked(async c=>{await c.query('BEGIN');try{await c.query('SELECT pg_advisory_xact_lock(781902641)');await checkAdmin(c,actor);
 if(d.candidateFingerprint){const item=(await c.query('SELECT id,name FROM wahi_v2.sales_items WHERE id=$1',[d.itemId])).rows[0];if(!item)throw fail('not_found');const t=await candidates.targets(c,new Date(this.cogs.clock()).toISOString()),fingerprint=candidates.hash([item.name,t.fingerprint,'v1']),a=candidates.classify(item,t.options);if(fingerprint!==d.candidateFingerprint||a.quality!=='EXACT'||a.candidates[0].key!==(d.menuItemId?'menu:'+d.menuItemId:'recipe:'+d.recipeId))throw fail('revision_conflict');}
 const result=await writePolicy(c,actor,d);await c.query('COMMIT');return result;
 }catch(e){await c.query('ROLLBACK');throw e;}});}
 async bulk(actor,input){authorize(actor,'reporting.configure');const d=z.object({confirmed:z.literal(true),entries:z.array(z.object({itemId,expectedVersion:z.number().int().nonnegative(),candidateFingerprint:z.string(),targetKey:z.string()}).strict()).min(1).max(500)}).strict().parse(input);if(new Set(d.entries.map(e=>e.itemId)).size!==d.entries.length)throw fail('invalid_request');return this.cogs.locked(async c=>{await c.query('BEGIN');try{await c.query('SELECT pg_advisory_xact_lock(781902641)');await checkAdmin(c,actor);const t=await candidates.targets(c,new Date(this.cogs.clock()).toISOString()),batch=crypto.randomUUID(),results=[];
 for(const entry of d.entries){const row=(await c.query("SELECT i.id,i.name,COALESCE(m.state,'unmapped') state FROM wahi_v2.sales_items i LEFT JOIN wahi_v2.cogs_mappings m ON m.item_id=i.id WHERE i.id=$1",[entry.itemId])).rows[0];if(!row||row.state!=='unmapped')throw fail('revision_conflict');const a=candidates.classify(row,t.options),target=a.candidates[0];if(a.quality!=='EXACT'||target.type!=='menu'||!target.portion||target.key!==entry.targetKey||candidates.hash([row.name,t.fingerprint,'v1'])!==entry.candidateFingerprint)throw fail('revision_conflict');results.push(await writePolicy(c,actor,{itemId:row.id,state:'mapped',expectedVersion:entry.expectedVersion,menuItemId:target.id,recipeId:null,quantity:null,unit:null,reason:'',confirmed:true},batch));}
 await c.query('COMMIT');return {committed:results.length,bulkId:batch,results};
 }catch(e){await c.query('ROLLBACK');throw e;}});}
 async history(actor,input){authorize(actor,'reporting.configure');itemId.parse(input.id);return {events:(await this.pool.query('SELECT actor_id,previous,next,recorded_at FROM wahi_v2.cogs_mapping_audit WHERE item_id=$1 ORDER BY recorded_at DESC,id DESC LIMIT 50',[input.id])).rows};}
}
module.exports={MappingReview,writePolicy,percentage};
