'use strict';
const crypto=require('node:crypto'),{z}=require('zod'),{authorize}=require('../auth'),{Exact:E}=require('../domain/exact'),{latest}=require('../domain/history'),{date,addDays,businessDate,fail}=require('../labor/model');
const {fetchDay}=require('./sales'),{readCostState}=require('./cost-state'),{costResolver,empty,addFact,encode,decode,unpack}=require('./cost');
const dates=z.object({start:z.string().refine(s=>{try{return !!date(s);}catch{return false;}}),end:z.string().refine(s=>{try{return !!date(s);}catch{return false;}})}).strict().refine(d=>d.start<=d.end);
const stats=()=>({databaseQueries:0,toastCalls:0,historicalResolutions:0,currentResolutions:0,materializedRowsCreated:0,materializedRowsRead:0});
function presentation(r){const qty=r.quantity,total=r.total;return {quantity:qty.decimal(20).replace(/\.?0+$/,''),total:total.decimal(12),average:qty.positive()?total.div(qty).decimal(12):null,displayTotal:total.decimal(2),displayAverage:qty.positive()?total.div(qty).decimal(2):null,netSales:r.netSalesKnown?r.netSales.decimal(12):null,percent:r.netSalesKnown&&r.netSales.positive()?total.div(r.netSales).mul('100').decimal(2):null,coverage:Object.fromEntries(['historical','current','alternate','unresolved'].map(k=>[k,{quantity:r[k].decimal(20).replace(/\.?0+$/,''),percent:qty.positive()?r[k].div(qty).mul('100').decimal(2):'0.00'}])),status:r.unresolved.positive()?'UNRESOLVED':r.current.positive()||r.alternate.positive()?'ESTIMATED':'HISTORICAL'};}
const percent=(n,d)=>d.positive()?n.div(d).mul('100').decimal(2):null;
function mappingPresentation(r,state){const p=presentation(r);if(state!=='mapped')return {...p,total:null,average:null,displayTotal:null,displayAverage:null,percent:null,costStatus:null,status:state==='unmapped'?'NEEDS_MAPPING':'IGNORED',coverage:Object.fromEntries(['historical','current','alternate','unresolved'].map(k=>[k,{quantity:'0',percent:null}]))};if(!r.quantity.positive())return {...p,total:null,displayTotal:null,percent:null,costStatus:null,status:'NO_MAPPED_SALES'};return {...p,costStatus:p.status};}
class TrueCogs{
 constructor(pool,client,{clock=()=>Date.now()}={}){Object.assign(this,{pool,client,clock});this.review=new (require('./mapping').MappingReview)(this);}
 async locked(fn,metrics){const raw=await this.pool.connect(),c=metrics?{query:(...args)=>{metrics.databaseQueries++;return raw.query(...args);},release:()=>raw.release()}:raw;let locked=false;try{locked=(await c.query('SELECT pg_try_advisory_lock(781902648) locked')).rows[0].locked;if(!locked)throw fail('report_busy');const result=await fn(c);if(metrics&&result?.stats)result.stats.databaseQueries=metrics.databaseQueries+1;return result;}finally{if(locked)await c.query('SELECT pg_advisory_unlock(781902648)');c.release();}}
 async settings(){const r=(await this.pool.query('SELECT timezone,closeout_hour FROM wahi_v2.labor_settings')).rows[0];if(!r?.timezone)throw fail('labor_sync_required');return {...r,today:businessDate(this.clock(),r.timezone,r.closeout_hour)};}
 async sync(actor,input){authorize(actor,'reporting.refresh');const d=dates.parse(input),config=await this.settings(),s=stats();s.databaseQueries++;if(d.end>config.today)throw fail('sales_future_date');return this.locked(async c=>{const start=performance.now();await c.query('UPDATE wahi_v2.sales_sync_state SET attempted_at=CURRENT_TIMESTAMP');let count=0;try{for(let day=d.start;day<=d.end&&count<3;day=addDays(day,1),count++){const fetched=await fetchDay(this.client,day,{onCall:()=>s.toastCalls++});await this.ingest(c,day,fetched,s);}await c.query('UPDATE wahi_v2.sales_sync_state SET failure_code=NULL');return {syncedDays:count,nextStart:addDays(d.start,count)<=d.end?addDays(d.start,count):null,stats:{...s,durationMs:performance.now()-start}};}catch(e){const code=['toast_auth_failed','toast_scope_missing','toast_rate_limited','sales_payload_unsupported','sales_business_date_mismatch','sales_page_limit','sales_duplicate_selection'].includes(e.code)?e.code:'sales_sync_failed';await c.query('UPDATE wahi_v2.sales_sync_state SET failure_code=$1',[code]);throw fail(code);}},s);}
 async ingest(c,day,{facts,orders,pages},s=stats()){
  const rows=facts.map(f=>({id:f.id,order_id:f.orderId,item_id:f.itemId,source:f,source_hash:crypto.createHash('sha256').update(JSON.stringify(f)).digest('hex')}));
  await c.query('BEGIN');try{
   const old=(await c.query('SELECT id,source_hash,present FROM wahi_v2.sales_facts WHERE business_date=$1',[day])).rows;
   const changed=old.filter(r=>r.present).length!==rows.length||rows.some(r=>!old.some(o=>o.id===r.id&&o.source_hash===r.source_hash&&o.present));
   const moved=(await c.query('SELECT DISTINCT business_date::text AS day FROM wahi_v2.sales_facts WHERE id=ANY($1::uuid[]) AND business_date<>$2::date',[rows.map(r=>r.id),day])).rows.map(r=>r.day);
   await c.query(`INSERT INTO wahi_v2.sales_items(id,name,group_id,name_observed_at,name_selection_id) SELECT DISTINCT ON (x->>'item_id') x->>'item_id',x->'source'->>'name',(x->'source'->>'groupId')::uuid,(x->'source'->>'saleAt')::timestamptz,(x->>'id')::uuid FROM jsonb_array_elements($1::jsonb) x ORDER BY x->>'item_id',x->'source'->>'saleAt' DESC,x->>'id' DESC ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,group_id=EXCLUDED.group_id,name_observed_at=EXCLUDED.name_observed_at,name_selection_id=EXCLUDED.name_selection_id,updated_at=CURRENT_TIMESTAMP WHERE (EXCLUDED.name_observed_at,EXCLUDED.name_selection_id)>=(wahi_v2.sales_items.name_observed_at,wahi_v2.sales_items.name_selection_id) OR wahi_v2.sales_items.name_observed_at IS NULL`,[JSON.stringify(rows)]);
   // Every new identity needs an explicit Admin decision, even a matching GUID.
   await c.query(`UPDATE wahi_v2.cogs_knowledge SET dirty=TRUE WHERE (business_date,item_id) IN (SELECT business_date,item_id FROM wahi_v2.sales_facts WHERE id=ANY($1::uuid[]) AND business_date<>$2::date)`,[rows.map(r=>r.id),day]);
   await c.query('UPDATE wahi_v2.sales_facts SET present=FALSE WHERE business_date=$1',[day]);
   await c.query(`INSERT INTO wahi_v2.sales_facts(id,order_id,item_id,business_date,source,source_hash) SELECT x.id,x.order_id,x.item_id,$2,x.source,x.source_hash FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,order_id uuid,item_id text,source jsonb,source_hash text) ON CONFLICT(id) DO UPDATE SET order_id=EXCLUDED.order_id,item_id=EXCLUDED.item_id,business_date=EXCLUDED.business_date,source=EXCLUDED.source,source_hash=EXCLUDED.source_hash,present=TRUE,synced_at=CURRENT_TIMESTAMP`,[JSON.stringify(rows),day]);
   await c.query(`INSERT INTO wahi_v2.sales_fact_versions(selection_id,source_hash,source) SELECT id,source_hash,source FROM wahi_v2.sales_facts WHERE business_date=$1 AND present ON CONFLICT DO NOTHING`,[day]);
   await c.query(`INSERT INTO wahi_v2.cogs_knowledge(business_date,item_id) SELECT DISTINCT business_date,item_id FROM wahi_v2.sales_facts WHERE business_date=$1 ON CONFLICT DO NOTHING`,[day]);
   if(changed)await c.query('UPDATE wahi_v2.cogs_knowledge SET dirty=TRUE WHERE business_date=$1',[day]);
   const affected=[day,...moved];await c.query('DELETE FROM wahi_v2.sales_item_days WHERE business_date=ANY($1::date[])',[affected]);
   await c.query(`INSERT INTO wahi_v2.sales_item_days SELECT business_date,item_id,sum((source->>'quantity')::numeric),CASE WHEN bool_and(source->>'netSales' IS NOT NULL) THEN sum((source->>'netSales')::numeric) END,count(*) FROM wahi_v2.sales_facts WHERE business_date=ANY($1::date[]) AND present AND source->>'reason' IS NULL GROUP BY business_date,item_id`,[affected]);
   await c.query('INSERT INTO wahi_v2.sales_sync_days VALUES($1,CURRENT_TIMESTAMP,$2,$3,$4) ON CONFLICT(business_date) DO UPDATE SET synced_at=EXCLUDED.synced_at,orders=EXCLUDED.orders,selections=EXCLUDED.selections,api_calls=EXCLUDED.api_calls',[day,orders,facts.length,pages]);await c.query('COMMIT');
  }catch(e){await c.query('ROLLBACK');throw e;}
 }
 async mapping(actor,input){return this.review.save(actor,input);}
 async mappings(actor,input){return this.review.list(actor,input);}
 async mappingBadge(actor){return this.review.badge(actor);}
 async mappingBulk(actor,input){return this.review.bulk(actor,input);}
 async mappingHistory(actor,input){return this.review.history(actor,input);}
 async rebuild(actor,input){authorize(actor,'reporting.read');const d=dates.parse(input),s=stats(),started=performance.now();return this.locked(async c=>{await c.query('BEGIN');try{await c.query('SELECT pg_advisory_xact_lock(781902641)');const now=new Date(this.clock()).toISOString(),work=(await c.query(`SELECT k.*,k.business_date::text AS day,m.state,m.recipe_id,m.menu_item_id,m.quantity::text,m.unit,m.mode,m.version FROM wahi_v2.cogs_knowledge k LEFT JOIN wahi_v2.cogs_mappings m ON m.item_id=k.item_id WHERE business_date BETWEEN $1 AND $2 AND (dirty OR valid_until<=$3) ORDER BY business_date,item_id LIMIT 200`,[d.start,d.end,now])).rows;const resolvers=new Map(),menuCache=new Map(),writes=[];const sources=(await c.query("SELECT f.business_date::text AS day,f.item_id,f.source FROM wahi_v2.sales_facts f JOIN jsonb_to_recordset($1::jsonb) x(day date,item_id text) ON f.business_date=x.day AND f.item_id=x.item_id WHERE f.present",[JSON.stringify(work.map(k=>({day:k.day,item_id:k.item_id})))])).rows;
 for(const k of work){const facts=sources.filter(f=>f.day===k.day&&f.item_id===k.item_id).map(r=>r.source).filter(f=>!f.reason);const out=empty();let target=null,resolver=null,menuExpiry=null,state=k.state||'unmapped';
  if(state==='mapped'){
   if(k.menu_item_id){if(!menuCache.has(k.menu_item_id))menuCache.set(k.menu_item_id,(await c.query('SELECT * FROM wahi_v2.menu_mappings WHERE menu_item_id=$1',[k.menu_item_id])).rows.map(r=>({...r,effectiveAt:r.effective_at?.toISOString()||null,recordedAt:r.recorded_at.toISOString(),supersedesId:r.supersedes_id})));const rows=menuCache.get(k.menu_item_id);menuExpiry=rows.map(r=>r.effectiveAt).filter(t=>t&&t>now).sort()[0]||null;const m=latest(rows,now,now);if(m)target={recipeId:m.recipe_id,quantity:m.quantity,unit:m.unit};}
   else target=k.mode==='execution'?{recipeId:k.recipe_id,mode:'execution'}:{recipeId:k.recipe_id,quantity:k.quantity,unit:k.unit};
   if(target){const key=JSON.stringify(target);if(!resolvers.has(key)){const recipe=(await c.query('SELECT output_ingredient_id FROM wahi_v2.recipes WHERE id=$1',[target.recipeId])).rows[0];if(recipe){target.outputIngredientId=recipe.output_ingredient_id;const snapshot=await readCostState(c,target.outputIngredientId);resolvers.set(key,costResolver(snapshot,target,now,s));}else resolvers.set(key,null);}resolver=resolvers.get(key);}
  }
  for(const f of facts){if(state!=='mapped'){out.quantity=out.quantity.add(f.quantity);if(f.netSales===null)out.netSalesKnown=false;else out.netSales=out.netSales.add(f.netSales);out.modifiers+=f.modifiers.length?1:0;continue;}addFact(out,f,resolver?resolver.at(f.saleAt):{level:'unresolved',cost:E.of('0'),references:[],blockers:[{reason:state==='unmapped'?'missing_recipe_mapping':state==='excluded'?'explicitly_excluded':'missing_menu_recipe_mapping'}]});}
  const payload={...encode(out),mappingState:state,mappingVersion:k.version||0,target,calculatedAt:now};if(state==='mapped'&&!out.historical.add(out.current).add(out.alternate).add(out.unresolved).eq(out.quantity))throw fail('cogs_reconciliation_failed');
  writes.push({day:k.day,item_id:k.item_id,payload,dependencies:resolver?.dependencies||[],menu_item_id:k.menu_item_id||null,valid_until:[resolver?.validUntil,menuExpiry].filter(Boolean).sort()[0]||null});s.materializedRowsCreated++;
 }
 await c.query(`UPDATE wahi_v2.cogs_knowledge k SET payload=x.payload,dependencies=x.dependencies,menu_item_id=x.menu_item_id,dirty=FALSE,generation=generation+1,generated_at=$2,valid_until=x.valid_until FROM jsonb_to_recordset($1::jsonb) x(day date,item_id text,payload jsonb,dependencies uuid[],menu_item_id uuid,valid_until timestamptz) WHERE k.business_date=x.day AND k.item_id=x.item_id`,[JSON.stringify(writes),now]);
 await c.query(`INSERT INTO wahi_v2.cogs_knowledge_history SELECT k.business_date,k.item_id,k.generation,k.payload,k.generated_at FROM wahi_v2.cogs_knowledge k JOIN jsonb_to_recordset($1::jsonb) x(day date,item_id text) ON k.business_date=x.day AND k.item_id=x.item_id`,[JSON.stringify(writes)]);
 await c.query('COMMIT');return {built:work.length,more:work.length===200,stats:{...s,durationMs:performance.now()-started}};}catch(e){await c.query('ROLLBACK');throw e;}},s);}
 async report(actor,input){authorize(actor,'reporting.read');const config=await this.settings(),d=dates.parse(input?.start?input:{start:config.today.slice(0,8)+'01',end:config.today}),started=performance.now();const [stored,days,diagnostics,sync]=await Promise.all([this.pool.query(`SELECT k.business_date::text,k.item_id,i.name,k.payload,k.dirty,k.valid_until,k.generated_at,COALESCE(m.state,'unmapped') current_state FROM wahi_v2.cogs_knowledge k JOIN wahi_v2.sales_items i ON i.id=k.item_id LEFT JOIN wahi_v2.cogs_mappings m ON m.item_id=k.item_id WHERE k.business_date BETWEEN $1 AND $2 ORDER BY i.name,k.business_date`,[d.start,d.end]),this.pool.query('SELECT business_date::text,synced_at FROM wahi_v2.sales_sync_days WHERE business_date BETWEEN $1 AND $2 ORDER BY business_date',[d.start,d.end]),this.pool.query(`SELECT source->>'reason' reason,count(*)::int selections,sum((source->>'quantity')::numeric)::text quantity FROM wahi_v2.sales_facts WHERE business_date BETWEEN $1 AND $2 AND present GROUP BY source->>'reason'`,[d.start,d.end]),this.pool.query('SELECT * FROM wahi_v2.sales_sync_state')]);const byItem=new Map(),totals=empty(),allSales=empty(),excluded=E.of('0');let excludedQty=excluded,mappedQty=E.of('0'),unmappedQty=E.of('0'),dirty=0;const mapping={mapped:new Set(),unmapped:new Set(),excluded:new Set()};
 for(const row of stored.rows){if(row.dirty||row.valid_until&&new Date(row.valid_until)<=this.clock())dirty++;if(!row.payload)continue;const p=decode(row.payload);p.mappingState=row.current_state;if(!p.quantity.positive())continue;mapping[p.mappingState].add(row.item_id);allSales.quantity=allSales.quantity.add(p.quantity);allSales.netSales=allSales.netSales.add(p.netSales);allSales.netSalesKnown&&=p.netSalesKnown;let item=byItem.get(row.item_id);if(!item){item={...empty(),id:row.item_id,name:row.name,mappingState:p.mappingState};byItem.set(row.item_id,item);}for(const target of [item,...(p.mappingState==='mapped'?[totals]:[])]){for(const key of ['quantity','total','netSales','historical','current','alternate','unresolved'])target[key]=target[key].add(p[key]);target.netSalesKnown&&=p.netSalesKnown;target.modifiers+=p.modifiers;}
 if(p.mappingState==='excluded')excludedQty=excludedQty.add(p.quantity);else if(p.mappingState==='mapped')mappedQty=mappedQty.add(p.quantity);else unmappedQty=unmappedQty.add(p.quantity);
 }
 const applicable=E.of(diagnostics.rows.find(r=>r.reason===null)?.quantity||'0'),reconciled=mappedQty.add(unmappedQty).add(excludedQty).eq(applicable)&&totals.historical.add(totals.current).add(totals.alternate).add(totals.unresolved).eq(totals.quantity);const required=Math.floor((Date.parse(d.end)-Date.parse(d.start))/86400000)+1;
 return {period:d,...config,rows:[...byItem.values()].map(r=>({id:r.id,name:r.name,mappingState:r.mappingState,...mappingPresentation(r,r.mappingState)})),summary:{...mappingPresentation(totals,'mapped'),applicableNetSales:allSales.netSalesKnown?allSales.netSales.decimal(12):null,mappingCoverage:{mapped:percent(mappedQty,applicable),needsMapping:percent(unmappedQty,applicable),ignored:percent(excludedQty,applicable)},netSalesMappingCoverage:allSales.netSalesKnown&&totals.netSalesKnown?percent(totals.netSales,allSales.netSales):null,mappedQuantity:mappedQty.decimal(20).replace(/\.?0+$/,''),unmappedQuantity:unmappedQty.decimal(20).replace(/\.?0+$/,''),excludedQuantity:excludedQty.decimal(20).replace(/\.?0+$/,''),applicableQuantity:applicable.decimal(20).replace(/\.?0+$/,''),modifierSelections:totals.modifiers},mapping:Object.fromEntries(Object.entries(mapping).map(([k,v])=>[k,v.size])),diagnostics:diagnostics.rows,missingDays:required-days.rows.length,lastSynced:days.rows.length?days.rows.reduce((a,r)=>a<r.synced_at?a:r.synced_at,days.rows[0].synced_at):null,dirtyRows:dirty,reconciled:reconciled&&dirty===0,syncFailure:sync.rows[0]?.failure_code,stats:{...stats(),databaseQueries:5,materializedRowsRead:stored.rows.length,durationMs:performance.now()-started}};
 }
 async detail(actor,input){authorize(actor,'reporting.read');const d=dates.parse({start:input.start,end:input.end});const rows=(await this.pool.query('SELECT business_date::text,dirty,payload,generation,generated_at FROM wahi_v2.cogs_knowledge WHERE item_id=$1 AND business_date BETWEEN $2 AND $3 ORDER BY business_date',[input.id,d.start,d.end])).rows;return {days:rows.map(r=>({...r,payload:r.payload?{mappingState:r.payload.mappingState,target:r.payload.target,...mappingPresentation(decode(r.payload),r.payload.mappingState),buckets:(r.payload.mappingState==='mapped'?r.payload.buckets:[]).map(b=>({...b,quantity:unpack(b.quantity).decimal(20),unitCost:unpack(b.unitCost).decimal(12)}))}:null}))};}
}
module.exports={TrueCogs,dates,presentation};
