'use strict';
const {Exact:E}=require('../domain/exact'),{groups,key,hints}=require('./composite'),{pack,unpack,empty,addFact}=require('./cost');
function optionName(groupPath,id){return hints.groups[groupPath?.at(-1)]?.options[id]?.name||'Unlabelled choice';}
function inspect(f,definition){
 const binding=definition.parents.find(p=>p.itemId===f.itemId),g=binding?groups(f.modifiers).get(key(binding.groupPath)):null,amounts=new Map();
 for(const o of g?.options||[])if(E.of(o.quantity).positive())amounts.set(o.itemId||'unidentified',(amounts.get(o.itemId||'unidentified')||E.of('0')).add(o.quantity));
 const ids=[...amounts.keys()].sort(),optionId=ids.length===1?ids[0]:null,alias=binding?.options.find(o=>o.optionId===optionId),choice=definition.choices.find(x=>x.key===alias?.choiceKey),issues=[];
 if(!ids.length)issues.push({reason:'variant_option_missing'});
 else if(ids.length!==1)issues.push({reason:'variant_options_conflicting',optionIds:ids});
 else if(!amounts.get(optionId).eq('1')&&!amounts.get(optionId).eq(f.quantity))issues.push({reason:'variant_option_quantity_invalid'});
 if(optionId&&!choice)issues.push({reason:'variant_option_unmapped',optionId,name:optionName(binding?.groupPath,optionId)});
 return {optionId,choice,issues,optionName:choice?.name||optionName(binding?.groupPath,optionId),canonical:JSON.stringify([binding?.groupPath||[],ids.map(id=>[id,pack(amounts.get(id))])])};
}
async function evaluator(c,definition,now,stats,resolvers=new Map()){
 const labels=await require('./choice-labels').read(c);const {costResolver}=require('./cost'),{readCostState}=require('./cost-state'),recipes=new Map();
 for(const choice of definition.choices){if(!resolvers.has(choice.recipeId)){const r=(await c.query('SELECT output_ingredient_id FROM wahi_v2.recipes WHERE id=$1',[choice.recipeId])).rows[0];resolvers.set(choice.recipeId,r?costResolver(await readCostState(c,r.output_ingredient_id),{recipeId:choice.recipeId,outputIngredientId:r.output_ingredient_id,mode:'execution'},now,stats):null);}recipes.set(choice.key,resolvers.get(choice.recipeId));}
 return {dependencies:[...new Set([...recipes.values()].flatMap(r=>r?.dependencies||[]))],validUntil:[...recipes.values()].map(r=>r?.validUntil).filter(Boolean).sort()[0]||null,run(f){const x=inspect(f,definition);for(const issue of x.issues)if(issue.optionId&&labels.has(issue.optionId))issue.name=labels.get(issue.optionId);const r=x.choice&&recipes.get(x.choice.key),evidence=x.issues.length?{level:'unresolved',cost:E.of('0'),references:[],blockers:x.issues}:r?r.at(f.saleAt):{level:'unresolved',cost:E.of('0'),references:[],blockers:[{reason:'missing_recipe_mapping',recipeId:x.choice?.recipeId}]};return {evidence,variant:{selectionId:f.id,parentId:f.itemId,saleAt:f.saleAt,parentQuantity:pack(E.of(f.quantity)),netSales:f.netSales,optionId:x.optionId,optionName:x.optionName,canonical:x.canonical,recipeId:x.issues.length?null:x.choice?.recipeId,executions:pack(x.issues.length?E.of('0'):E.of(f.quantity)),mappingComplete:!x.issues.length,issues:x.issues,evidence:{...evidence,cost:pack(evidence.cost)},total:pack(E.of(f.quantity).mul(evidence.cost))}};}};
}
function aggregate(facts,runner){const out=empty();out.variants=[];for(const f of facts){const {evidence,variant}=runner.run(f);addFact(out,f,evidence);out.variants.push(variant);if(!variant.mappingComplete){out.mappingUnresolved=out.mappingUnresolved.add(f.quantity);if(f.netSales!==null)out.mappingUnresolvedSales=out.mappingUnresolvedSales.add(f.netSales);}}return out;}
function describe(rows=[]){let total=E.of('0'),resolved=E.of('0'),unresolved=E.of('0');const choices=new Map(),warnings=new Map();for(const r of rows){const q=unpack(r.parentQuantity);total=total.add(q);if(r.mappingComplete){resolved=resolved.add(q);const k=r.optionId+'|'+r.recipeId;if(!choices.has(k))choices.set(k,{optionId:r.optionId,name:r.optionName,recipeId:r.recipeId,quantity:E.of('0')});choices.get(k).quantity=choices.get(k).quantity.add(q);}else{unresolved=unresolved.add(q);for(const issue of r.issues){const k=issue.reason+'|'+(issue.optionId||'');if(!warnings.has(k))warnings.set(k,{...issue,quantity:E.of('0')});warnings.get(k).quantity=warnings.get(k).quantity.add(q);}}}const dec=x=>x.decimal(20);return {selections:rows.length,total:dec(total),resolved:dec(resolved),unresolved:dec(unresolved),reconciled:total.eq(resolved.add(unresolved)),complete:!unresolved.positive(),choices:[...choices.values()].map(x=>({...x,quantity:dec(x.quantity),exactExecutions:pack(x.quantity)})),warnings:[...warnings.values()].map(x=>({...x,quantity:dec(x.quantity)})),costUnresolved:rows.filter(r=>r.mappingComplete&&r.evidence.level==='unresolved')};}
module.exports={inspect,evaluator,aggregate,describe,optionName};
