'use strict';
const crypto=require('node:crypto'),{z}=require('zod'),{authorize}=require('../auth');
const fail=code=>Object.assign(new Error(code),{code});
const configSchema=z.object({enabled:z.boolean(),apiEnvironment:z.enum(['sandbox','production']),apiHost:z.string().max(250).refine(value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&u.pathname==='/'&&!u.search&&!u.hash&&(u.hostname==='toasttab.com'||u.hostname.endsWith('.toasttab.com'));}catch{return false;}}),clientId:z.string().trim().min(1).max(500),restaurantGuid:z.union([z.literal(''),z.string().uuid()])}).strict();
const inputSchema=z.object({expectedVersion:z.number().int().nonnegative(),config:configSchema,clientSecret:z.string().min(1).max(8192).optional()}).strict();
function keyBytes(encoded){if(!encoded||! /^[A-Za-z0-9+/]{43}=$/.test(encoded))throw fail('integration_key_unavailable');const key=Buffer.from(encoded,'base64');if(key.length!==32)throw fail('integration_key_unavailable');return key;}
function seal(secret,key,context){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(Buffer.from(context));const ciphertext=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return {version:1,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),ciphertext:ciphertext.toString('base64')};}
function unseal(value,key,context){try{const decipher=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(value.iv,'base64'));decipher.setAAD(Buffer.from(context));decipher.setAuthTag(Buffer.from(value.tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(value.ciphertext,'base64')),decipher.final()]).toString('utf8');}catch{throw fail('integration_secret_unavailable');}}
class ToastSettings {
 constructor(pool,{environment,key}){if(!['local-review','staging','production'].includes(environment))throw fail('invalid_integration_environment');this.pool=pool;this.environment=environment;this.key=key?keyBytes(key):null;}
 context(){return 'wahi:toast:'+this.environment+':v1';}
 async read(actor){authorize(actor,'integrations.manage');const row=(await this.pool.query('SELECT config, version, updated_at, sealed_secret IS NOT NULL AS secret_configured FROM wahi_v2.integration_settings WHERE environment=$1 AND name=$2',[this.environment,'toast'])).rows[0];const audit=(await this.pool.query('SELECT actor_id,event,details,recorded_at FROM wahi_v2.integration_audit WHERE environment=$1 AND name=$2 ORDER BY recorded_at DESC LIMIT 30',[this.environment,'toast'])).rows;return {environment:this.environment,name:'Toast',version:row?.version||0,config:row?.config||null,secretConfigured:row?.secret_configured||false,status:row?.secret_configured?'Configured':'Not configured',lastTest:null,testSupported:false,keyAvailable:!!this.key,updatedAt:row?.updated_at||null,audit};}
 async save(actor,input){authorize(actor,'integrations.manage');let data;try{data=inputSchema.parse(input);}catch{throw fail('invalid_integration_configuration');}if(!this.key)throw fail('integration_key_unavailable');const client=await this.pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(781902642)');const old=(await client.query('SELECT * FROM wahi_v2.integration_settings WHERE environment=$1 AND name=$2 FOR UPDATE',[this.environment,'toast'])).rows[0];if((old?.version||0)!==data.expectedVersion)throw fail('revision_conflict');let secret=old?.sealed_secret||null;
 if(data.clientSecret!==undefined)secret=seal(data.clientSecret,this.key,this.context());
 if(data.config.enabled&&!secret)throw fail('integration_secret_required');
 const version=(old?.version||0)+1,now=new Date().toISOString();await client.query('INSERT INTO wahi_v2.integration_settings(environment,name,config,sealed_secret,version,updated_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(environment,name) DO UPDATE SET config=EXCLUDED.config,sealed_secret=EXCLUDED.sealed_secret,version=EXCLUDED.version,updated_at=EXCLUDED.updated_at',[this.environment,'toast',JSON.stringify(data.config),secret?JSON.stringify(secret):null,version,now]);
 const events=[['configuration_updated',{before:old?.config||null,after:data.config}]];if((old?.config.enabled||false)!==data.config.enabled)events.push([data.config.enabled?'enabled':'disabled',{}]);if(data.clientSecret!==undefined)events.push([old?.sealed_secret?'secret_replaced':'secret_configured',{}]);for(const [event,details]of events)await client.query('INSERT INTO wahi_v2.integration_audit(id,environment,name,actor_id,event,details,recorded_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[crypto.randomUUID(),this.environment,'toast',actor.id,event,JSON.stringify(details),now]);await client.query('COMMIT');return {saved:true,version};
 }catch(e){await client.query('ROLLBACK');if(['revision_conflict','integration_secret_required'].includes(e.code))throw e;throw fail('integration_save_failed');}finally{client.release();}}
 // Future server-side consumers only. No HTTP route invokes or returns this.
 async credentialsForService(){if(!this.key)throw fail('integration_key_unavailable');const row=(await this.pool.query('SELECT config,sealed_secret FROM wahi_v2.integration_settings WHERE environment=$1 AND name=$2',[this.environment,'toast'])).rows[0];if(!row?.config.enabled||!row.sealed_secret)throw fail('integration_not_configured');return {...row.config,clientSecret:unseal(row.sealed_secret,this.key,this.context()),userAccessType:'TOAST_MACHINE_CLIENT'};}
}
module.exports={ToastSettings,configSchema,inputSchema,seal,unseal,keyBytes};
