'use strict';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function canonicalOrigin(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.pathname!=='/'||u.search||u.hash||['localhost','127.0.0.1','[::1]'].includes(u.hostname))throw new Error('Invalid email application origin');return u.origin;}
function template(purpose,{origin,token,username}={}){
 const definitions={setup:['Set up your Wahi account','A Wahi Hana account was created for you. Choose a password to finish setting up your account.','Set up account','account-setup','24 hours'],verification:['Verify your Wahi email address','Please verify this email address for your Wahi Hana account.','Verify Email','verify-email','24 hours'],reset:['Reset your Wahi password','A password reset was requested for your Wahi Hana account.','Reset Password','reset-password','1 hour'],test:['Wahi email test successful','Wahi Hana can send transactional email using the configured email service.']};
 const d=definitions[purpose];if(!d)throw new Error('Invalid email purpose');let link;
 if(purpose!=='test'){if(!/^[A-Za-z0-9_-]{43}$/.test(token))throw new Error('Invalid email token');link=canonicalOrigin(origin)+'/#'+d[3]+'?token='+token;}
 const tail=link?`This link expires in ${d[4]}. If you were not expecting this message, you can ignore it.`:'';
 const loginName=purpose==='setup'&&username?'Your username: '+username:'';
 return {subject:d[0],text:['Wahi Hana',d[0],d[1],loginName,link?d[2]+': '+link:'',tail].filter(Boolean).join('\n\n'),html:`<!doctype html><html><body style="margin:0;background:#f5f4ef;font-family:Arial,sans-serif;color:#183a35"><table role="presentation" width="100%"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" style="max-width:560px;background:white"><tr><td style="padding:32px"><p style="letter-spacing:2px;font-weight:bold">WAHI HANA</p><h1 style="font-size:26px">${escape(d[0])}</h1><p style="line-height:1.6">${escape(d[1])}</p>${loginName?`<p>${escape(loginName)}</p>`:''}${link?`<p style="padding:16px 0"><a href="${escape(link)}" style="display:inline-block;background:#183a35;color:white;padding:14px 22px;text-decoration:none;border-radius:5px">${escape(d[2])}</a></p><p style="line-height:1.6;color:#555">${escape(tail)}</p><p style="font-size:12px;word-break:break-all">If the button does not work, copy this link:<br>${escape(link)}</p>`:''}</td></tr></table></td></tr></table></body></html>`};
}
module.exports={template,canonicalOrigin};
