'use strict';
const crypto=require('node:crypto'),{z}=require('zod'),{authorize}=require('../auth');
const {date,addDays,businessDate,weekFor,weekEnd,amount,aggregate,fail}=require('./model');
const dateValue=z.string().refine(s=>{try{date(s);return true;}catch{return false;}}),hours=z.string().max(30).refine(s=>{try{return amount(s).nonnegative()&&amount('100000').sub(s).nonnegative();}catch{return false;}});
const stamp=v=>v?new Date(v).toISOString():null;
const dateRows=rows=>rows.map(r=>({...r,...Object.fromEntries(['effective_date','week_date','business_date'].filter(k=>r[k]).map(k=>[k,typeof r[k]==='string'?r[k].slice(0,10):r[k].toISOString().slice(0,10)])),...(r.recorded_at?{recorded_at:stamp(r.recorded_at)}:{})}));
class LaborService{
 constructor(pool,client,{clock=()=>Date.now()}={}){this.pool=pool;this.client=client;this.clock=clock;}
 async transaction(fn){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(781902644)');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async audit(c,actor,event,details){await c.query('INSERT INTO wahi_v2.labor_audit(id,actor_id,event,details) VALUES($1,$2,$3,$4)',[crypto.randomUUID(),actor.id,event,JSON.stringify(details)]);}
 async settings(){return (await this.pool.query('SELECT * FROM wahi_v2.labor_settings')).rows[0];}
 async policy(actor){authorize(actor,'labor.read');const [settings,rules,jobs,mappings,targets,sync]=await Promise.all([this.settings(),this.pool.query('SELECT *,effective_date::text FROM wahi_v2.labor_week_rules ORDER BY recorded_at'),this.pool.query('SELECT guid,name,active,synced_at FROM wahi_v2.labor_jobs ORDER BY name'),this.pool.query('SELECT *,effective_date::text FROM wahi_v2.labor_classifications ORDER BY recorded_at'),this.pool.query('SELECT *,week_date::text,foh::text,boh::text FROM wahi_v2.labor_targets ORDER BY recorded_at'),this.pool.query('SELECT * FROM wahi_v2.labor_sync_state')]);return {settings,rules:dateRows(rules.rows),jobs:jobs.rows,mappings:dateRows(mappings.rows),targets:dateRows(targets.rows),sync:sync.rows[0],today:settings.timezone?businessDate(this.clock(),settings.timezone,settings.closeout_hour):null};}
 async configure(actor,kind,input){authorize(actor,'labor.configure');const schemas={week:z.object({effectiveDate:dateValue,weekStart:z.number().int().min(0).max(6)}).strict(),mapping:z.object({effectiveDate:dateValue,assignments:z.array(z.object({jobGuid:z.string().uuid(),area:z.enum(['FOH','BOH','Excluded','Unassigned'])}).strict()).min(1).max(200)}).strict(),target:z.object({week:dateValue,foh:hours,boh:hours,expectedId:z.string().uuid().nullable()}).strict()};if(!schemas[kind])throw fail('invalid_request');const d=schemas[kind].parse(input);return this.transaction(async c=>{
 if(kind==='week'){const s=(await c.query('SELECT * FROM wahi_v2.labor_settings')).rows[0];if(!s.timezone)throw fail('labor_sync_required');const existing=(await c.query('SELECT * FROM wahi_v2.labor_week_rules')).rows;if(new Date(d.effectiveDate+'T12:00:00Z').getUTCDay()!==d.weekStart)throw fail('invalid_week_start');if(existing.length&&d.effectiveDate<=businessDate(this.clock(),s.timezone,s.closeout_hour))throw fail('labor_future_policy_required');if(existing.length){const latest=dateRows(existing).sort((a,b)=>b.effective_date.localeCompare(a.effective_date))[0];if(d.effectiveDate<=latest.effective_date)throw fail('labor_future_policy_required');const used=(await c.query('SELECT 1 FROM wahi_v2.labor_targets WHERE week_date >= $1 LIMIT 1',[addDays(d.effectiveDate,-6)])).rowCount;if(used)throw fail('labor_target_conflict');}await c.query('INSERT INTO wahi_v2.labor_week_rules(id,effective_date,week_start,actor_id) VALUES($1,$2,$3,$4)',[crypto.randomUUID(),d.effectiveDate,d.weekStart,actor.id]);await this.audit(c,actor,'week_start_changed',d);}
 if(kind==='mapping'){if(new Set(d.assignments.map(x=>x.jobGuid)).size!==d.assignments.length)throw fail('invalid_request');for(const a of d.assignments){const latest=(await c.query('SELECT effective_date::text FROM wahi_v2.labor_classifications WHERE job_guid=$1 ORDER BY effective_date DESC LIMIT 1',[a.jobGuid])).rows[0];if(latest){const s=(await c.query('SELECT * FROM wahi_v2.labor_settings')).rows[0];if(d.effectiveDate<=latest.effective_date||d.effectiveDate<=businessDate(this.clock(),s.timezone,s.closeout_hour))throw fail('labor_future_policy_required');}await c.query('INSERT INTO wahi_v2.labor_classifications(id,job_guid,effective_date,area,actor_id) VALUES($1,$2,$3,$4,$5)',[crypto.randomUUID(),a.jobGuid,d.effectiveDate,a.area,actor.id]);await this.audit(c,actor,'job_classification_changed',{...a,effectiveDate:d.effectiveDate});}}
 if(kind==='target'){const rules=dateRows((await c.query('SELECT *,effective_date::text FROM wahi_v2.labor_week_rules')).rows);if(weekFor(d.week,rules)!==d.week)throw fail('invalid_week_start');const last=(await c.query('SELECT id FROM wahi_v2.labor_targets WHERE week_date=$1 ORDER BY recorded_at DESC LIMIT 1',[d.week])).rows[0];if((last?.id||null)!==d.expectedId)throw fail('revision_conflict');const id=crypto.randomUUID();await c.query('INSERT INTO wahi_v2.labor_targets(id,week_date,foh,boh,actor_id) VALUES($1,$2,$3,$4,$5)',[id,d.week,d.foh,d.boh,actor.id]);await this.audit(c,actor,'weekly_foh_target_changed',{week:d.week,hours:d.foh,id});await this.audit(c,actor,'weekly_boh_target_changed',{week:d.week,hours:d.boh,id});}return {saved:true};});}
 async overview(actor,selected){authorize(actor,'labor.read');const settings=await this.settings(),today=settings.timezone?businessDate(this.clock(),settings.timezone,settings.closeout_hour):null,day=selected?date(selected):today;
 const [ruleRows,syncRows]=await Promise.all([this.pool.query(`(SELECT *,effective_date::text FROM wahi_v2.labor_week_rules WHERE effective_date <= $1 ORDER BY wahi_v2.labor_week_rules.effective_date DESC,recorded_at DESC LIMIT 1) UNION ALL (SELECT *,effective_date::text FROM wahi_v2.labor_week_rules WHERE effective_date > $1 ORDER BY wahi_v2.labor_week_rules.effective_date,recorded_at DESC LIMIT 1)`,[day||'1970-01-01']),this.pool.query('SELECT * FROM wahi_v2.labor_sync_state')]);const rules=dateRows(ruleRows.rows),sync=syncRows.rows[0],p={settings,today,sync},week=day?weekFor(day,rules):null;if(!week)return {...p,week:null,metrics:null,status:today?'week_not_configured':'not_synced'};
 const end=weekEnd(week,rules);const [entries,jobs,mappings,targets,daysResult]=await Promise.all([this.pool.query('SELECT guid,job_guid,business_date::text,in_date,out_date,regular_hours,overtime_hours,breaks,deleted,synced_at FROM wahi_v2.labor_entries WHERE business_date BETWEEN $1 AND $2 AND NOT deleted',[week,end]),this.pool.query('SELECT guid,name FROM wahi_v2.labor_jobs'),this.pool.query(`(SELECT DISTINCT ON(job_guid) *,effective_date::text FROM wahi_v2.labor_classifications WHERE effective_date < $1 ORDER BY job_guid,wahi_v2.labor_classifications.effective_date DESC,recorded_at DESC) UNION ALL (SELECT *,effective_date::text FROM wahi_v2.labor_classifications WHERE effective_date BETWEEN $1 AND $2)`,[week,end]),this.pool.query('SELECT *,week_date::text,foh::text,boh::text FROM wahi_v2.labor_targets WHERE week_date=$1 ORDER BY recorded_at DESC LIMIT 1',[week]),this.pool.query('SELECT business_date::text,synced_at FROM wahi_v2.labor_sync_days WHERE business_date BETWEEN $1 AND $2',[week,end])]);
 const days=daysResult.rows,required=[];for(let d=week;d<=end&&d<=today;d=addDays(d,1))required.push(d);const complete=required.length>0&&required.every(d=>days.some(x=>x.business_date===d)),target=dateRows(targets.rows)[0]||null;const freshest=days.length?Math.min(...days.map(x=>new Date(x.synced_at).getTime())):null,current=end>=today,stale=!freshest||(current&&this.clock()-freshest>10*60000)||!!sync.error_code;
 return {...p,week,end,target,coverageComplete:complete,lastSynced:freshest?new Date(freshest).toISOString():null,stale,status:complete?(sync.error_code?'sync_failed':stale?'stale':'ready'):'data_unavailable',metrics:complete?aggregate(dateRows(entries.rows),jobs.rows,dateRows(mappings.rows),target,this.clock()):null};}
 async refresh(actor,selected){authorize(actor,'labor.refresh');const c=await this.pool.connect();let locked=false;try{locked=(await c.query('SELECT pg_try_advisory_lock(781902645) AS locked')).rows[0].locked;if(!locked)return {status:'sync_in_progress'};const prev=(await c.query('SELECT * FROM wahi_v2.labor_sync_state')).rows[0];if(prev.attempted_at&&this.clock()-new Date(prev.attempted_at).getTime()<60000)return {status:'refresh_limited'};await c.query('UPDATE wahi_v2.labor_sync_state SET attempted_at=$1',[new Date(this.clock())]);
 try{const config=await this.client.connection();const settings=await this.settings();if(settings.restaurant_guid&&settings.restaurant_guid!==config.restaurantGuid)throw fail('toast_restaurant_changed');let meta=null;const refreshMeta=!prev.metadata_at||this.clock()-new Date(prev.metadata_at).getTime()>86400000;if(refreshMeta){const r=await this.client.request('/restaurants/v1/restaurants/'+encodeURIComponent(config.restaurantGuid));if(r.guid!==config.restaurantGuid||!r.general?.timeZone||!Number.isInteger(r.general.closeoutHour))throw fail('toast_payload_unsupported');businessDate(this.clock(),r.general.timeZone,r.general.closeoutHour);const jobs=await this.client.request('/labor/v1/jobs'),employees=await this.client.request('/labor/v1/employees');if(!Array.isArray(jobs)||!Array.isArray(employees)||jobs.length>2000||employees.length>10000)throw fail('toast_payload_unsupported');meta={timezone:r.general.timeZone,closeout:r.general.closeoutHour,jobs,employees};}
 const timezone=meta?.timezone||settings.timezone,cutoff=meta?.closeout??settings.closeout_hour;if(settings.timezone&&(settings.timezone!==timezone||settings.closeout_hour!==cutoff))throw fail('toast_business_day_changed');const today=businessDate(this.clock(),timezone,cutoff),rules=dateRows((await c.query('SELECT *,effective_date::text FROM wahi_v2.labor_week_rules')).rows),week=selected?weekFor(date(selected),rules):weekFor(today,rules),start=week||addDays(today,-6),end=week?weekEnd(start,rules):addDays(start,6);if(start>today)throw fail('labor_future_sync');const fetched=[];for(let day=start;day<=end&&day<=today;day=addDays(day,1)){const entries=await this.client.request('/labor/v1/timeEntries?businessDate='+day.replaceAll('-','')+'&includeArchived=true&includeMissedBreaks=true');if(!Array.isArray(entries)||entries.length>10000)throw fail('toast_payload_unsupported');fetched.push({day,entries});}
 const known=meta?meta.jobs.map(j=>j.guid):(await c.query('SELECT guid FROM wahi_v2.labor_jobs')).rows.map(j=>j.guid),missing=[...new Set(fetched.flatMap(f=>f.entries.map(e=>e.jobReference?.guid).filter(Boolean)))].filter(g=>!known.includes(g)),extraJobs=[];for(let i=0;i<missing.length;i+=100){const result=await this.client.request('/labor/v1/jobs?jobIds='+encodeURIComponent(missing.slice(i,i+100).join(',')));if(!Array.isArray(result))throw fail('toast_payload_unsupported');extraJobs.push(...result);}if(missing.some(g=>!extraJobs.some(j=>j.guid===g)))throw fail('toast_payload_unsupported');
 const now=new Date(this.clock());await this.transaction(async tx=>{if(meta){await tx.query('UPDATE wahi_v2.labor_settings SET restaurant_guid=$1,timezone=$2,closeout_hour=$3',[config.restaurantGuid,timezone,cutoff]);await tx.query('UPDATE wahi_v2.labor_jobs SET active=FALSE,synced_at=$2 WHERE NOT(guid=ANY($1::text[]))',[meta.jobs.map(j=>j.guid),now]);for(const j of meta.jobs){if(!z.string().uuid().safeParse(j.guid).success||typeof j.title!=='string')throw fail('toast_payload_unsupported');await tx.query('INSERT INTO wahi_v2.labor_jobs(guid,name,active,modified_at,synced_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(guid) DO UPDATE SET name=EXCLUDED.name,active=EXCLUDED.active,modified_at=EXCLUDED.modified_at,synced_at=EXCLUDED.synced_at',[j.guid,j.title,!j.deleted,j.modifiedDate||null,now]);}for(const e of meta.employees){if(!z.string().uuid().safeParse(e.guid).success)throw fail('toast_payload_unsupported');await tx.query('INSERT INTO wahi_v2.labor_employees(guid,active,job_guids,modified_at,synced_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(guid) DO UPDATE SET active=EXCLUDED.active,job_guids=EXCLUDED.job_guids,modified_at=EXCLUDED.modified_at,synced_at=EXCLUDED.synced_at',[e.guid,!e.deleted,JSON.stringify((e.jobReferences||[]).map(j=>j.guid)),e.modifiedDate||null,now]);}}
 for(const j of extraJobs){if(!z.string().uuid().safeParse(j.guid).success||typeof j.title!=='string')throw fail('toast_payload_unsupported');await tx.query('INSERT INTO wahi_v2.labor_jobs(guid,name,active,modified_at,synced_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(guid) DO UPDATE SET name=EXCLUDED.name,active=EXCLUDED.active,modified_at=EXCLUDED.modified_at,synced_at=EXCLUDED.synced_at',[j.guid,j.title,!j.deleted,j.modifiedDate||null,now]);}
 for(const {day,entries}of fetched){for(const e of entries){if(!z.string().uuid().safeParse(e.guid).success||e.businessDate!==day.replaceAll('-','')||!Number.isFinite(Date.parse(e.inDate)))throw fail('toast_payload_unsupported');const breaks=Array.isArray(e.breaks)?e.breaks.map(b=>({paid:b.paid,inDate:b.inDate,outDate:b.outDate,missed:b.missed,waived:b.waived})):null;await tx.query('INSERT INTO wahi_v2.labor_entries(guid,restaurant_guid,business_date,job_guid,employee_guid,in_date,out_date,regular_hours,overtime_hours,breaks,deleted,modified_at,synced_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(guid) DO UPDATE SET business_date=EXCLUDED.business_date,job_guid=EXCLUDED.job_guid,employee_guid=EXCLUDED.employee_guid,in_date=EXCLUDED.in_date,out_date=EXCLUDED.out_date,regular_hours=EXCLUDED.regular_hours,overtime_hours=EXCLUDED.overtime_hours,breaks=EXCLUDED.breaks,deleted=EXCLUDED.deleted,modified_at=EXCLUDED.modified_at,synced_at=EXCLUDED.synced_at',[e.guid,config.restaurantGuid,day,e.jobReference?.guid||null,e.employeeReference?.guid||null,e.inDate,e.outDate,e.regularHours,e.overtimeHours,JSON.stringify(breaks),!!e.deleted,e.modifiedDate||null,now]);}await tx.query('UPDATE wahi_v2.labor_entries SET deleted=TRUE,synced_at=$3 WHERE business_date=$1 AND NOT(guid=ANY($2::text[]))',[day,entries.map(e=>e.guid),now]);await tx.query('INSERT INTO wahi_v2.labor_sync_days(business_date,synced_at) VALUES($1,$2) ON CONFLICT(business_date) DO UPDATE SET synced_at=EXCLUDED.synced_at',[day,now]);}await tx.query('UPDATE wahi_v2.labor_sync_state SET synced_at=$1,error_code=NULL,metadata_at=CASE WHEN $2 THEN $1 ELSE metadata_at END',[now,!!meta]);});return {status:'synced',days:fetched.length};
 }catch(e){const allowed=['toast_restaurant_missing','toast_restaurant_changed','toast_business_day_changed','toast_payload_unsupported','toast_auth_failed','toast_scope_missing','toast_rate_limited','toast_unavailable','toast_pagination_unsupported','integration_not_configured','integration_key_unavailable','integration_secret_unavailable','labor_future_sync'];const code=allowed.includes(e.code)?e.code:'toast_sync_failed';await c.query('UPDATE wahi_v2.labor_sync_state SET error_code=$1',[code]);return {status:'failed',error:code};}
 }finally{if(locked)await c.query('SELECT pg_advisory_unlock(781902645)');c.release();}}
}
module.exports={LaborService,dateRows};
