'use strict';
const {fail}=require('./model');
// Keep numeric API lexemes exact rather than parsing worked hours as binary floats.
function parseToast(text){return JSON.parse(text,(key,value,context)=>{if(['regularHours','overtimeHours'].includes(key)&&typeof value==='number'){if(!context?.source)throw fail('toast_payload_unsupported');return expandDecimal(context.source);}return value;});}
function expandDecimal(s){const m=/^(-?)(\d+)(?:\.(\d+))?(?:[eE]([+-]?\d+))?$/.exec(s);if(!m)throw fail('toast_payload_unsupported');const frac=m[3]||'',exponent=Number(m[4]||0);if(Math.abs(exponent)>40)throw fail('toast_payload_unsupported');const digits=m[2]+frac,point=m[2].length+exponent;return m[1]+(point<=0?'0.'+'0'.repeat(-point)+digits:point>=digits.length?digits+'0'.repeat(point-digits.length):digits.slice(0,point)+'.'+digits.slice(point));}
class ToastLaborClient{
 constructor(settings,{fetcher=fetch}={}){this.settings=settings;this.fetch=fetcher;this.token=null;}
 async connection(){const c=await this.settings.credentialsForService();if(!c.restaurantGuid)throw fail('toast_restaurant_missing');return c;}
 async request(path){const c=await this.connection();const identity=c.apiHost+'|'+c.clientId+'|'+c.clientSecret;if(!this.token||this.token.identity!==identity||this.token.until<Date.now()){let r;try{r=await this.fetch(new URL('/authentication/v1/authentication/login',c.apiHost),{method:'POST',redirect:'error',signal:AbortSignal.timeout(15000),headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:c.clientId,clientSecret:c.clientSecret,userAccessType:'TOAST_MACHINE_CLIENT'})});}catch{throw fail('toast_unavailable');}if(!r.ok)throw fail(r.status===401?'toast_auth_failed':'toast_unavailable');const data=await r.json();if(!data.token?.accessToken)throw fail('toast_auth_failed');this.token={identity,value:data.token.accessToken,until:Date.now()+Math.min(Number(data.token.expiresIn)||3600,86400)*1000-60000};}
 let r;try{r=await this.fetch(new URL(path,c.apiHost),{method:'GET',redirect:'error',signal:AbortSignal.timeout(20000),headers:{Authorization:'Bearer '+this.token.value,'Toast-Restaurant-External-ID':c.restaurantGuid}});}catch{throw fail('toast_unavailable');}if(!r.ok){if(r.status===401)this.token=null;throw fail(r.status===401?'toast_auth_failed':r.status===403?'toast_scope_missing':r.status===429?'toast_rate_limited':'toast_unavailable');}if(r.headers.get('link')||r.headers.get('toast-next-page-token'))throw fail('toast_pagination_unsupported');const text=await r.text();if(text.length>12000000)throw fail('toast_payload_unsupported');try{return parseToast(text);}catch{throw fail('toast_payload_unsupported');}}
}
module.exports={ToastLaborClient,parseToast,expandDecimal};
