'use strict';
// Explicitly invoked owner-review validation. Local HTTP only; retain price audit.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {Exact:E}=require('../domain/exact');
async function run(){const root=path.join(__dirname,'.runtime'),base='http://127.0.0.1:4317';const credentials=JSON.parse(await fs.readFile(path.join(root,'access.json'))).find(a=>a.username==='owner');const login=await fetch(base+'/api/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({username:credentials.username,password:credentials.password})});if(!login.ok)throw Error('Login failed');const cookie=login.headers.get('set-cookie').split(';')[0];let csrf;
async function api(route,input){const response=await fetch(base+'/api/'+route,{method:input?'POST':'GET',headers:{Cookie:cookie,Origin:base,'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(input?{body:JSON.stringify(input)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error);return data;}
csrf=(await api('me')).csrf;const cat=await api('catalog'),ingredient=cat.ingredients.find(i=>i.name==='Demerara Sugar'),direct=cat.recipes.find(r=>r.name==='Demerara Syrup'),downstream=cat.recipes.find(r=>r.name==='Mai Tai');const detail=await api('item?id='+ingredient.id),p=detail.packages.find(p=>p.id===detail.basis.purchaseOptionId),time=new Date().toISOString();
async function values(){const item=await api('item?id='+ingredient.id),m=await api('management'),d=m.recipes.find(r=>r.id===direct.id),down=m.recipes.find(r=>r.id===downstream.id);return {purchase:item.packages.find(x=>x.id===p.id).price.amount,base:(await api('cost?id='+ingredient.id+'&quantity=1&unit='+p.contentUnit)).completeCost,direct:d.cost.completeCost,downstream:down.cost.completeCost};}
const before=await values();let changed,restored;const provenance={kind:'manual_verification',reference:'Owner-requested live cost-propagation validation; temporary price then restored'};
try{await api('domain/command',{command:'addPrice',input:{purchaseOptionId:p.id,amount:E.of(p.price.amount).mul('2').decimal(),currency:p.price.currency,provenance,note:'VALIDATION ONLY: temporary doubled price; original price will be restored.'}});changed=await values();assert.ok(E.of(changed.base).eq(E.of(before.base).mul('2'))||E.of(changed.base).sub(E.of(before.base).mul('2')).abs().decimal(10)==='0.0000000000');assert.notEqual(changed.direct,before.direct);assert.notEqual(changed.downstream,before.downstream);const historical=await api('cost?id='+ingredient.id+'&quantity=1&unit='+p.contentUnit+'&at='+encodeURIComponent(time));assert.equal(historical.completeCost,before.base);
}finally{await api('domain/command',{command:'addPrice',input:{purchaseOptionId:p.id,amount:p.price.amount,currency:p.price.currency,provenance,note:'VALIDATION COMPLETE: restored original current purchase price; retain temporary audit history.'}});restored=await values();assert.deepEqual(restored,before);}
const result={status:'PASS',ingredient:ingredient.name,packageQuantity:p.contentQuantity,packageUnit:p.contentUnit,direct:direct.name,downstream:downstream.name,before,changed,restored,originalStateRestored:true};await fs.writeFile(path.join(root,'current-cost-validation.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}
run().catch(e=>{console.error(e.message);process.exitCode=1;});
